window.KAVYA_JOBS_DB = {
  "lastUpdated": "2026-08-18T08:39:09.291Z",
  "sourceHealth": {
    "swedish": "healthy",
    "medicon": "healthy",
    "dutch": "healthy",
    "germany": "healthy",
    "danish": "healthy",
    "uk": "healthy",
    "nature": "healthy",
    "switzerland": "healthy",
    "austria": "healthy",
    "norway": "healthy",
    "finland": "healthy",
    "industry": "healthy",
    "epfl": "healthy",
    "leibniz": "healthy",
    "academics": "healthy"
  },
  "jobs": [
    {
      "id": "swedish-uppsala-university--forskningsassistent-inom-in-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Uppsala University",
      "score": 83,
      "title": "Forskningsassistent inom in-cell-NMR av RNA-dynamik",
      "tags": [
        "🏢 Industry",
        "📍 Uppsala"
      ],
      "why": "Institutionen för medicinsk biokemi och mikrobiologi (IMBIM) vid Uppsala universitet utgör en bred internationell miljö för forskning och undervisning. Vid IMBI…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:949924/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.002Z",
      "dateFound": "2026-08-18T08:41:18.002Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--administrat-r",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Uppsala University",
      "score": 85,
      "title": "Administratör",
      "tags": [
        "🏢 Industry",
        "📍 Uppsala"
      ],
      "why": "Institutionen för immunologi, genetik och patologi vid Uppsala universitet har en bred forskningsprofil med starka forskargrupper inriktade på bl. a cancer, gen…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:954966/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.007Z",
      "dateFound": "2026-08-18T08:41:18.007Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--doktorand",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Uppsala University",
      "score": 100,
      "title": "Doktorand",
      "tags": [
        "🎓 PhD",
        "📍 Uppsala"
      ],
      "why": "Doktorand i medicinsk cellbiologi med inriktning mot studier av interventioner vid behandling av typ 1 diabetes Institutionen för medicinsk cellbiologi vid Upps…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:953668/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.012Z",
      "dateFound": "2026-08-18T08:41:18.012Z",
      "roleType": "phd",
      "domain": "toxicology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--i-datoriserad-bildbehandling",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Uppsala University",
      "score": 100,
      "title": "Doktorand i datoriserad bildbehandling med fokus på tillämpningar inom datadriven precisionsmedicin",
      "tags": [
        "🎓 PhD",
        "📍 Uppsala"
      ],
      "why": "Är du intresserad av att utveckla nya metoder för bildanalys och maskininlärning för precisionsmedicin och kliniskt beslutsstöd? Vill du vara en del av ett fors…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:955187/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.014Z",
      "dateFound": "2026-08-18T08:41:18.014Z",
      "roleType": "phd",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--projektassistent-inom-cell-och-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Lund University",
      "score": 85,
      "title": "Projektassistent inom cell- och virusmekanik för antiviral utveckling och förbättrad produktion av genterapivektorer",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Anställningen är placerad vid BMC (Biomedicinskt centrum) i Lund, specifikt inom Neurobiologi-sektionen vid Institutionen för Exper…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:959675/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.022Z",
      "dateFound": "2026-08-18T08:41:18.022Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--klinisk-assistent-molekyl-r-ske",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Lund University",
      "score": 55,
      "title": "Klinisk assistent - Molekylär skelettbiologi",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Om tjänsten Vi söker en person för att arbeta med ett projekt inom vävnadsteknik med mänskligt ben respektive benmärg. Arbetet kommer att omfatta specifika cell…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:958675/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.029Z",
      "dateFound": "2026-08-18T08:41:18.029Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--bioinformatiker-i-klinisk-genet",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Lund University",
      "score": 70,
      "title": "Bioinformatiker i klinisk genetik",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Vid Avdelningen för klinisk genetik, Institutionen för laboratoriemedicin, söker vi en bioinformatiker som ska arbeta med att utvec…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:958694/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.032Z",
      "dateFound": "2026-08-18T08:41:18.032Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--projektassistenter-s-kes-till-p",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Lund University",
      "score": 58,
      "title": "Projektassistenter sökes till projekt",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Vi söker nu sex projektassistenter till projektet \"Navigering av rättsliga problem utan lag\" Forskningsprojektet Studier om tillgång till rättvisa tyder på att …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:958502/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.036Z",
      "dateFound": "2026-08-18T08:41:18.036Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--medicinsk-vetenskap-inom-moleky",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Lund University",
      "score": 96,
      "title": "Doktorand medicinsk vetenskap inom molekylär epidemiologi",
      "tags": [
        "🎓 PhD",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Forskargruppen Integrative Pancreatic Cancer Research (iPanCare) vid Institutionen för translationell medicin, Medicinska fakultete…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:958015/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.039Z",
      "dateFound": "2026-08-18T08:41:18.039Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--klinisk-assistent-inom-tum-rmik",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Lund University",
      "score": 65,
      "title": "Klinisk assistent inom Tumörmikromiljö",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Om forskargruppen Forskargruppen bedriver forskning inom hjärntumörer och lungcancer. Medarbetarna är disputerade läkare, postdocs, doktorander, forskningsingen…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:947106/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.041Z",
      "dateFound": "2026-08-18T08:41:18.041Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--ekonom-vid-institutionen-f-r-la",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Lund University",
      "score": 60,
      "title": "Ekonom vid institutionen för laboratoriemedicin",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Beskrivning arbetsplatsen Institutionen för laboratoriemedicin (ILM) är en av sju institutioner vid Medicinska fakulteten. Vi bedriver ledande forskning inom de…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:949772/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.048Z",
      "dateFound": "2026-08-18T08:41:18.048Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--plattformsansvarig-vid-multipar",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Lund University",
      "score": 90,
      "title": "Plattformsansvarig vid MultiPark",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen MultiPark är ett strategiskt forskningsområde vid Lunds universitet. Som en global ledare inom forskningen om Parkinsons, Alzheimer…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:947666/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.050Z",
      "dateFound": "2026-08-18T08:41:18.050Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--project-coordinator-for-l",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 73,
      "title": "Project Coordinator for Large Research Study on Human intestinal diseases",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Do you want to contribute to top quality medical research? We are seeking a highly organized and motivated Project Coordinator to join our multi-laboratory team…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:960143/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.054Z",
      "dateFound": "2026-08-18T08:41:18.054Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--amanuens-inom-biostatisti",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 60,
      "title": "Amanuens inom biostatistik och klinisk epidemiologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för medicinsk epidemiologi och biostatistik bedriver forskning inom epidemiologi och biost…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:959843/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.055Z",
      "dateFound": "2026-08-18T08:41:18.055Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-inom-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 91,
      "title": "Forskningsassistent inom vaccinimmunologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? En tjänst som forskningsassistent är nu ledig i professor Karin Lorés forskargrupp för att stödja labora…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:958516/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.056Z",
      "dateFound": "2026-08-18T08:41:18.056Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 63,
      "title": "Forskningsassistent",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för molekylär medicin och kirurgi söker en forskningsassistent med inriktning mot barncanc…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:959432/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.057Z",
      "dateFound": "2026-08-18T08:41:18.057Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--amanuens-till-institution",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 85,
      "title": "Amanuens till institutionen för mikrobiologi, tumör- och cellbiologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för mikrobiologi, tumör- och cellbiologi (MTC) vid Karolinska Institutet bedriver forsknin…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:959288/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.059Z",
      "dateFound": "2026-08-18T08:41:18.059Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--systemutvecklare-till-cen",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 60,
      "title": "Systemutvecklare till centrum för eliminering av livmoderhalscancer",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? Vi söker en systemutvecklare till professor Joakim Dillners forskargrupp vid centrum för eliminering av livmo…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:957990/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.065Z",
      "dateFound": "2026-08-18T08:41:18.065Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-till-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 93,
      "title": "Forskningsassistent till avdelningen biomolekylär och cellulär medicin",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? Institutionen för laboratoriemedicin består av sju avdelningar som bedriver både forskning och undervisning. …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:949820/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.066Z",
      "dateFound": "2026-08-18T08:41:18.066Z",
      "roleType": "research-assistant",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-inom-",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 63,
      "title": "Forskningsassistent inom miljömedicin",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? I vår forskargrupp finner du en unik möjlighet att arbeta tätt tillsammans med etablerade forskare inom neuro…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:957549/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.067Z",
      "dateFound": "2026-08-18T08:41:18.067Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--biomedicinsk-systemutveck",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 60,
      "title": "Biomedicinsk systemutvecklare till CLINTEC",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? Som biomedicinsk systemutvecklare kommer du arbeta i doktor Mikael Bensons forskningsgrupp för medicinska dig…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:957295/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.068Z",
      "dateFound": "2026-08-18T08:41:18.068Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-till-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 100,
      "title": "Forskningsassistent till laboratorieverksamhet med inriktning immunologi och flödescytometri",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? Vid enheten för öron-, näs- och halssjukdomar vid institutionen för klinisk vetenskap, intervention och tekni…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:957446/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.070Z",
      "dateFound": "2026-08-18T08:41:18.070Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-till-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 83,
      "title": "Forskningsassistent till enheten för kirurgi och onkologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Vill du arbeta i gränslandet mellan cancerforskning, bildanalys och statistik? Nu söker enheten för kiru…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:948582/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.075Z",
      "dateFound": "2026-08-18T08:41:18.075Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--the-field-of-brain-immuno",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 100,
      "title": "Research Assistant in the field of brain immunology",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Do you want to contribute to top quality medical research? The Sten Linnarsson lab is a part of Unit of Molecular Neurobiology at the Department of Medical Bioc…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:957251/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.076Z",
      "dateFound": "2026-08-18T08:41:18.076Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--genome-replication",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 88,
      "title": "Research assistant in genome replication",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Do you want to contribute to innovative cancer research Join us at Karolinska Institutet and SciLifeLab, two top-ranked institutions for the advancement of mole…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:956985/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.079Z",
      "dateFound": "2026-08-18T08:41:18.079Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--within-the-section-of-pha",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 71,
      "title": "Research Assistant within the Section of Pharmacogenetics",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Do you want to contribute to top quality medical research? We invite applications for a Research Assistant position in the research group of Professor Magnus In…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:953591/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.087Z",
      "dateFound": "2026-08-18T08:41:18.087Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-inom-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 83,
      "title": "Forskningsassistent inom bioinformatik med tillämpning av maskininlärning i reglerande genomik.",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för cell -och molekylärbiologi (CMB) är en institution med fokus på grundforskning. CMB be…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:953974/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.089Z",
      "dateFound": "2026-08-18T08:41:18.089Z",
      "roleType": "research-assistant",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--research-infrastructure-s",
      "country": "sweden",
      "tier": "high",
      "type": "industry",
      "org": "Karolinska Institutet",
      "score": 83,
      "title": "Research Infrastructure specialist",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Do you want to contribute to top quality medical research? The Chemical Biology Consortium Sweden (CBCS) is a national research infrastructure providing state-o…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:952428/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.091Z",
      "dateFound": "2026-08-18T08:41:18.091Z",
      "roleType": "industry-scientist",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-i-sys",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 53,
      "title": "Forskningsassistent i systemneurovetenskap Neurala grunder för överlevnadsbeteenden",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Stagkourakis-laboratoriet, som ligger i toppmoderna faciliteter i gränssnittet mellan Karolinska Institu…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:929940/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.095Z",
      "dateFound": "2026-08-18T08:41:18.095Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-stockholm-university--forskningsassistent",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Stockholm University",
      "score": 63,
      "title": "Forskningsassistent",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Institutionen för biokemi och biofysik, institutionens lokaler ligger huvudsakligen i Arrheniuslaboratorierna tillsammans med de andra kemiinstitutionerna och a…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://su.varbi.com/en/what:job/jobID:958671/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.099Z",
      "dateFound": "2026-08-18T08:41:18.099Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-stockholm-university--i-v-xtfysiologi",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Stockholm University",
      "score": 100,
      "title": "Doktorand i växtfysiologi",
      "tags": [
        "🎓 PhD",
        "📍 Stockholm"
      ],
      "why": "Institutionen för ekologi, miljö och botanik (DEEP) bedriver forskning och utbildning vid Arrheniuslaboratorierna på campus Frescati. Vi är cirka 100 medarbetar…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://su.varbi.com/en/what:job/jobID:949863/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.107Z",
      "dateFound": "2026-08-18T08:41:18.107Z",
      "roleType": "phd",
      "domain": "epigenetics",
      "sourceType": "academic"
    },
    {
      "id": "swedish-stockholm-university--i-milj-vetenskap-fokus-p-k",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Stockholm University",
      "score": 95,
      "title": "Doktorand i miljövetenskap, fokus på korruption i EU:s kemikaliereglering",
      "tags": [
        "🎓 PhD",
        "📍 Stockholm"
      ],
      "why": "Institutionen för miljövetenskap är en av de större institutionerna inom Naturvetenskapliga fakulteten. Institutionen består av fyra enheter med drygt 170 anstä…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://su.varbi.com/en/what:job/jobID:945197/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.110Z",
      "dateFound": "2026-08-18T08:41:18.110Z",
      "roleType": "phd",
      "domain": "toxicology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-stockholm-university--i-milj-vetenskap-aerosol-m",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Stockholm University",
      "score": 60,
      "title": "Doktorand i miljövetenskap, aerosol-molnväxelverkan i klimatmodeller",
      "tags": [
        "🎓 PhD",
        "📍 Stockholm"
      ],
      "why": "Institutionen för miljövetenskap är en av de större institutionerna inom Naturvetenskapliga fakulteten. Institutionen består av fyra enheter med drygt 170 anstä…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://su.varbi.com/en/what:job/jobID:944721/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-08-18T08:41:18.110Z",
      "dateFound": "2026-08-18T08:41:18.110Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "medicon-knightec-group--valideringsingenj-r-life-science",
      "country": "sweden",
      "tier": "stretch",
      "type": "industry",
      "org": "Knightec Group",
      "score": 40,
      "title": "Valideringsingenjör Life Science",
      "tags": [
        "🏢 Industry",
        "📍 Lund, Sweden"
      ],
      "why": "Scraped from medicon. Rule-based score: 40 matches Kavya's profile keywords.",
      "deadline": "📅 6 September 2026",
      "deadlineWarn": false,
      "url": "https://www.mediconvillage.se/job/valideringsingenjor-life-science-10/",
      "source": "live",
      "sourceName": "medicon",
      "portal": "Medicon Village",
      "fetchedAt": "2026-08-17T08:47:46.480Z",
      "dateFound": "2026-08-17T08:47:46.480Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "medicon-knightec-group--konsult-inom-life-science",
      "country": "sweden",
      "tier": "stretch",
      "type": "industry",
      "org": "Knightec Group",
      "score": 40,
      "title": "Konsult inom Life Science",
      "tags": [
        "🏢 Industry",
        "📍 Lund, Sweden"
      ],
      "why": "Scraped from medicon. Rule-based score: 40 matches Kavya's profile keywords.",
      "deadline": "📅 6 September 2026",
      "deadlineWarn": false,
      "url": "https://www.mediconvillage.se/job/konsult-inom-life-science-12/",
      "source": "live",
      "sourceName": "medicon",
      "portal": "Medicon Village",
      "fetchedAt": "2026-08-17T08:47:46.481Z",
      "dateFound": "2026-08-17T08:47:46.481Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "medicon-best-talent-a-s--manager-of-qc-laboratory",
      "country": "sweden",
      "tier": "stretch",
      "type": "industry",
      "org": "Best Talent A/S",
      "score": 40,
      "title": "Manager of QC Laboratory",
      "tags": [
        "🏢 Industry",
        "📍 Lund, Sweden"
      ],
      "why": "Scraped from medicon. Rule-based score: 40 matches Kavya's profile keywords.",
      "deadline": "📅 31 August 2026",
      "deadlineWarn": false,
      "url": "https://www.mediconvillage.se/job/manager-of-qc-laboratory/",
      "source": "live",
      "sourceName": "medicon",
      "portal": "Medicon Village",
      "fetchedAt": "2026-08-17T08:47:46.481Z",
      "dateFound": "2026-08-17T08:47:46.481Z",
      "roleType": "qa-qc",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "medicon-camurus--senior-research-scientist-peptide-analy",
      "country": "sweden",
      "tier": "medium",
      "type": "industry",
      "org": "Camurus",
      "score": 63,
      "title": "Senior Research Scientist – Peptide Analysis & Analytical Development",
      "tags": [
        "🏢 Industry",
        "📍 Lund, Sweden"
      ],
      "why": "Scraped from medicon. Rule-based score: 63 matches Kavya's profile keywords.",
      "deadline": "📅 30 August 2026",
      "deadlineWarn": false,
      "url": "https://www.mediconvillage.se/job/senior-research-scientist-peptide-analysis-analytical-development/",
      "source": "live",
      "sourceName": "medicon",
      "portal": "Medicon Village",
      "fetchedAt": "2026-08-17T08:47:46.481Z",
      "dateFound": "2026-08-17T08:47:46.481Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "medicon-camurus--senior-research-scientist-peptide-chemi",
      "country": "sweden",
      "tier": "stretch",
      "type": "industry",
      "org": "Camurus",
      "score": 48,
      "title": "Senior Research Scientist – Peptide Chemistry & Formulation",
      "tags": [
        "🏢 Industry",
        "📍 Lund, Sweden"
      ],
      "why": "Scraped from medicon. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 30 August 2026",
      "deadlineWarn": false,
      "url": "https://www.mediconvillage.se/job/senior-research-scientist-peptide-chemistry-formulation/",
      "source": "live",
      "sourceName": "medicon",
      "portal": "Medicon Village",
      "fetchedAt": "2026-08-17T08:47:46.481Z",
      "dateFound": "2026-08-17T08:47:46.481Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "dutch-erasmus-mc--dc13-the-epitranscriptome-of-prostat",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Erasmus MC",
      "score": 95,
      "title": "PhD student (DC13) The epitranscriptome of prostate cancer progression",
      "tags": [
        "🎓 PhD",
        "📍 Rotterdam"
      ],
      "why": "Are you ready to join The MSCA-DN European Epitranscriptomics of Cancer Academy? We are seeking a highly motivated PhD candidate to join the Marie Skłodowska-Cu…",
      "deadline": "31 Aug 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/360725/phd-student-dc13-the-epitranscriptome-of-prostate-cancer-progression/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-08-18T08:41:18.130Z",
      "dateFound": "2026-08-18T08:41:18.130Z",
      "roleType": "phd",
      "domain": "epigenetics",
      "sourceType": "academic"
    },
    {
      "id": "dutch-maastricht-university--the-impact-of-indoor-air-",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Maastricht University",
      "score": 100,
      "title": "PhD Candidate: The Impact of Indoor Air Pollution on Lung Health in a Changing Climate",
      "tags": [
        "🎓 PhD",
        "📍 Maastricht"
      ],
      "why": "Welcome to Maastricht University! Do you want to contribute to healthier living environments and help uncover how climate change affects respiratory health? We …",
      "deadline": "30 Aug 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/362892/phd-candidate-the-impact-of-indoor-air-pollution-on-lung-health-in-a-changing-climate/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-08-18T08:41:18.132Z",
      "dateFound": "2026-08-18T08:41:18.132Z",
      "roleType": "phd",
      "domain": "toxicology",
      "sourceType": "academic"
    },
    {
      "id": "dutch-maastricht-university--the-field-of-induced-plur",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Maastricht University",
      "score": 100,
      "title": "PhD Candidate in the field of induced pluripotent stem cells and organoids",
      "tags": [
        "🎓 PhD",
        "📍 Maastricht",
        "Stem Cells"
      ],
      "why": "Welcome to Maastricht University! How can we guide stem cells to develop into different cell lineages by using mechanical stimulation? Join our interdisciplinar…",
      "deadline": "23 Aug 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/363022/phd-candidate-in-the-field-of-induced-pluripotent-stem-cells-and-organoids/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-08-18T08:41:18.134Z",
      "dateFound": "2026-08-18T08:41:18.134Z",
      "roleType": "phd",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "dutch-maastricht-university--bioengineering-autonomic-",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Maastricht University",
      "score": 80,
      "title": "PhD Candidate Bioengineering Autonomic Innervation & Optogenetic Control in 3D Tissue Models",
      "tags": [
        "🎓 PhD",
        "📍 Maastricht"
      ],
      "why": "Welcome to Maastricht University! Help us build the first optogenetically controllable model of sympathetic innervation in engineered 3D tissue, combining stem …",
      "deadline": "15 Sept 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/363328/phd-candidate-bioengineering-autonomic-innervation-optogenetic-control-in-3d-tissue-models/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-08-18T08:41:18.136Z",
      "dateFound": "2026-08-18T08:41:18.136Z",
      "roleType": "phd",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "dutch-hubrecht-institute--hubrecht-international-phd-p",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Hubrecht Institute",
      "score": 85,
      "title": "Hubrecht International PhD Program (HIPP) - Utrecht",
      "tags": [
        "🎓 PhD",
        "📍 Utrecht"
      ],
      "why": "Launch Your Scientific Career in a World-Class Research Environment Are you an ambitious student eager to push the frontiers of molecular and developmental biol…",
      "deadline": "15 Sept 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/362912/hubrecht-international-phd-program-hipp-utrecht/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-08-18T08:41:18.136Z",
      "dateFound": "2026-08-18T08:41:18.136Z",
      "roleType": "phd",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "dutch-leiden-university--genetic-susceptibility-in-ste",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Universiteit Leiden",
      "score": 95,
      "title": "PhD candidate Genetic Susceptibility in Stem Cell-Derived Organoid Safety Testing",
      "tags": [
        "🎓 PhD",
        "📍 Leiden",
        "Stem Cells"
      ],
      "why": "The Faculty of Science and the Division of Cell Systems and Drug Safety is looking for a: PhD candidate Genetic Susceptibility in Stem Cell-Derived Organoid Saf…",
      "deadline": "21 Aug 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/362667/phd-candidate-genetic-susceptibility-in-stem-cell-derived-organoid-safety-testing/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-08-18T08:41:18.138Z",
      "dateFound": "2026-08-18T08:41:18.138Z",
      "roleType": "phd",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "dutch-sanquin-bloedvoorziening--scientist-lipid-nanopa",
      "country": "netherlands",
      "tier": "medium",
      "type": "phd",
      "org": "Sanquin Bloedvoorziening",
      "score": 71,
      "title": "Scientist Lipid Nanoparticle Gene Therapy",
      "tags": [
        "🏢 Industry",
        "📍 Amsterdam"
      ],
      "why": "Sanquin Blood Supply Foundation uniquely combines medical, diagnostic, blood bank, and research activities. With 2,000 committed colleagues and 345,000 blood do…",
      "deadline": "26 Aug 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/363020/scientist-lipid-nanoparticle-gene-therapy/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-08-18T08:41:18.138Z",
      "dateFound": "2026-08-18T08:41:18.138Z",
      "roleType": "junior-scientist",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "dutch-leiden-university--research-technician-in-vivo-p",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Universiteit Leiden",
      "score": 88,
      "title": "Research Technician in vivo pharmacology (0.8 fte)",
      "tags": [
        "🏢 Industry",
        "📍 Leiden"
      ],
      "why": "The division of Systems Pharmacology and Pharmacy of the Leiden Academic Centre for Drug Research (LACDR) at Leiden University is recruiting a research technici…",
      "deadline": "11 Sept 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/363268/research-technician-in-vivo-pharmacology-08-fte/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-08-18T08:41:18.140Z",
      "dateFound": "2026-08-18T08:41:18.140Z",
      "roleType": "technician",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--statens-naturhistorisk",
      "country": "denmark",
      "tier": "stretch",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 55,
      "title": "Statens Naturhistoriske Museums kommercielle afdeling søger salgsorienteret Butik Floor Manager med fokus på lagerdrift",
      "tags": [
        "🏢 Industry",
        "📍 Copenhagen, Denmark"
      ],
      "why": "Statens Naturhistoriske Museum står overfor et spændende år. I første halvdel af 2027 åbner vi dørene til et helt nyt museum, hvor vi for første gang nogensinde…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=165840",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-08-18T08:41:18.141Z",
      "dateFound": "2026-08-18T08:41:18.141Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--synaptic-neurobiology-",
      "country": "denmark",
      "tier": "high",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 100,
      "title": "Research Assistant in Synaptic Neurobiology at the Department of Neuroscience",
      "tags": [
        "🏢 Industry",
        "📍 Copenhagen, Denmark"
      ],
      "why": "We are looking for a highly motivated and independent Research Assistant to support an ongoing research project investigating local presynaptic protein synthesi…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=166548",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-08-18T08:41:18.143Z",
      "dateFound": "2026-08-18T08:41:18.143Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--dopamine-addiction-bio",
      "country": "denmark",
      "tier": "high",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 90,
      "title": "PhD fellowship in dopamine addiction biology at Department of Neuroscience",
      "tags": [
        "🎓 PhD",
        "📍 Copenhagen, Denmark"
      ],
      "why": "Faculty of Health and Medical Sciences University of Copenhagen We are offering a three-years PhD fellowship in dopamine addiction biology commencing November 1…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=166624",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-08-18T08:41:18.145Z",
      "dateFound": "2026-08-18T08:41:18.145Z",
      "roleType": "phd",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--laboratory-assistant-i",
      "country": "denmark",
      "tier": "medium",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 60,
      "title": "Laboratory assistant in the Blackford Group, Department of Cellular and Molecular Medicine (ICMM)",
      "tags": [
        "🏢 Industry",
        "📍 Copenhagen, Denmark"
      ],
      "why": "The research group of Andrew Blackford is looking for a motivated laboratory assistant . The position is available from October 1st, 2026, or soon thereafter . …",
      "deadline": "August 22, 2026",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=166647",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-08-18T08:41:18.148Z",
      "dateFound": "2026-08-18T08:41:18.148Z",
      "roleType": "technician",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--at-university-of-copen",
      "country": "denmark",
      "tier": "high",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 100,
      "title": "Research Assistant at University of Copenhagen",
      "tags": [
        "🏢 Industry",
        "📍 Copenhagen, Denmark"
      ],
      "why": "A highly attractive Research Assistant position is available in the Choudhary group at the Novo Nordisk Foundation Center for Protein Research (CPR – www.cpr.ku…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=167075",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-08-18T08:41:18.149Z",
      "dateFound": "2026-08-18T08:41:18.149Z",
      "roleType": "research-assistant",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--virus-host-interaction",
      "country": "denmark",
      "tier": "high",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 100,
      "title": "PhD fellowship in virus-host interactions at the Department of Immunology and Microbiology",
      "tags": [
        "🎓 PhD",
        "📍 Copenhagen, Denmark"
      ],
      "why": "We are offering a PhD fellowship in virus-host interactions commencing 15 November 2026 or as soon as possible thereafter. Our group and research During the PhD…",
      "deadline": "31 August 2026",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=164943",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-08-18T08:41:18.156Z",
      "dateFound": "2026-08-18T08:41:18.156Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--biophysics",
      "country": "denmark",
      "tier": "medium",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 70,
      "title": "PhD Fellowship in BioPhysics",
      "tags": [
        "🎓 PhD",
        "📍 Copenhagen, Denmark"
      ],
      "why": "The Niels Bohr Institute, Faculty of Science at University of Copenhagen invites applicants for a PhD fellowship in computational modelling of active materials …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=166288",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-08-18T08:41:18.159Z",
      "dateFound": "2026-08-18T08:41:18.159Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "uk-university-of-cambridge--senior-research-laborat",
      "country": "united kingdom",
      "tier": "medium",
      "type": "phd",
      "org": "University of Cambridge",
      "score": 75,
      "title": "Senior Research Laboratory Technician - Tissue Culture and Media Kitchen (Fixed Term)",
      "tags": [
        "🏢 Industry",
        "📍 Cambridge"
      ],
      "why": "MRC Toxicology Unit, Central Cambridge. Salary: £31,236 to £35,608 per annum…",
      "deadline": "06 Sep",
      "deadlineWarn": false,
      "url": "https://www.jobs.ac.uk/job/DSO984/senior-research-laboratory-technician-tissue-culture-and-media-kitchen-fixed-term",
      "source": "live",
      "sourceName": "uk",
      "portal": "FindAPhD (UK)",
      "fetchedAt": "2026-08-18T08:41:18.163Z",
      "dateFound": "2026-08-18T08:41:18.163Z",
      "roleType": "technician",
      "domain": "toxicology",
      "sourceType": "academic"
    },
    {
      "id": "uk-ucl--career-development-fellowships-in-the-depar",
      "country": "united kingdom",
      "tier": "medium",
      "type": "phd",
      "org": "UCL",
      "score": 75,
      "title": "Career Development Fellowships in the Department of Cell and Developmental Biology",
      "tags": [
        "🏢 Industry",
        "📍 London"
      ],
      "why": "Scraped from uk. Rule-based score: 75 matches Kavya's profile keywords.",
      "deadline": "31 Aug",
      "deadlineWarn": false,
      "url": "https://www.jobs.ac.uk/job/DRY651/career-development-fellowships-in-the-department-of-cell-and-developmental-biology",
      "source": "live",
      "sourceName": "uk",
      "portal": "FindAPhD (UK)",
      "fetchedAt": "2026-08-18T08:41:18.164Z",
      "dateFound": "2026-08-18T08:41:18.164Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "uk-university-of-cambridge--research-laboratory-flo",
      "country": "united kingdom",
      "tier": "stretch",
      "type": "phd",
      "org": "University of Cambridge",
      "score": 45,
      "title": "Research Laboratory Floor Coordinator",
      "tags": [
        "🏢 Industry",
        "📍 Cambridge"
      ],
      "why": "Cambridge Stem Cell Institute (SBS). Salary: £31,236 to £35,608…",
      "deadline": "23 Aug",
      "deadlineWarn": false,
      "url": "https://www.jobs.ac.uk/job/DSK883/research-laboratory-floor-coordinator",
      "source": "live",
      "sourceName": "uk",
      "portal": "FindAPhD (UK)",
      "fetchedAt": "2026-08-18T08:41:18.164Z",
      "dateFound": "2026-08-18T08:41:18.164Z",
      "roleType": "research-assistant",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "uk-daphne-jackson-trust--daphne-jackson-fellowship-",
      "country": "united kingdom",
      "tier": "stretch",
      "type": "phd",
      "org": "Daphne Jackson Trust",
      "score": 55,
      "title": "Daphne Jackson Fellowship (0.6 FTE)",
      "tags": [
        "🏢 Industry",
        "📍 Plymouth"
      ],
      "why": "Plymouth Brain Tumour Research Centre. Salary: £34,308 to £39,745 Dependent on qualifications, between spinal point 29 (£34,308 pro rata) and spinal point 34 (£…",
      "deadline": "28 Sep",
      "deadlineWarn": false,
      "url": "https://www.jobs.ac.uk/job/DSM793/daphne-jackson-fellowship-06-fte",
      "source": "live",
      "sourceName": "uk",
      "portal": "FindAPhD (UK)",
      "fetchedAt": "2026-08-18T08:41:18.165Z",
      "dateFound": "2026-08-18T08:41:18.165Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "austria-university-of-vienna--research-technician-biomar",
      "country": "austria",
      "tier": "medium",
      "type": "phd",
      "org": "CeMM Vienna",
      "score": 70,
      "title": "Research Technician Biomarker-directed precision therapeutics for childhood cancers for AITHYRA and CeMM (m/f/d)",
      "tags": [
        "🏢 Industry",
        "📍 Vienna, Austria"
      ],
      "why": "Full-time employee, Vienna #Laboratory #Molecular Biology #Cell Culture Technology…",
      "deadline": "📅 Start: 01 October 2026",
      "deadlineWarn": false,
      "url": "https://cemm.at/open-positions/qdkbwxln8ornz6znv2h8dnmstzrsin7",
      "source": "live",
      "sourceName": "austria",
      "portal": "CeMM Vienna",
      "fetchedAt": "2026-08-18T08:41:18.179Z",
      "dateFound": "2026-08-18T08:41:18.179Z",
      "roleType": "technician",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-h-gskolen-i-molde--stilling-i-logistikk-med-foku",
      "country": "norway",
      "tier": "medium",
      "type": "phd",
      "org": "Høgskolen i Molde",
      "score": 65,
      "title": "Stipendiatstilling i logistikk med fokus på flaskehalser i petroleumssektoren",
      "tags": [
        "🎓 PhD",
        "📍 Molde"
      ],
      "why": "Stipendiatstilling i logistikk med fokus på flaskehalser i petroleumssektoren Høgskolen i Molde søker Om oss Om stillingen / arbeidsoppgaver Mens energiomstilli…",
      "deadline": "📅 15.09.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/305563",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.193Z",
      "dateFound": "2026-08-18T08:41:18.193Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-h-gskolen-i-molde--stilling-i-logistikk-med-foku",
      "country": "norway",
      "tier": "medium",
      "type": "phd",
      "org": "Høgskolen i Molde",
      "score": 65,
      "title": "Stipendiatstilling i logistikk med fokus på intelligent anskaffelse",
      "tags": [
        "🎓 PhD",
        "📍 Molde"
      ],
      "why": "Stipendiatstilling i logistikk med fokus på intelligent anskaffelse Høgskolen i Molde søker Om oss Om stillingen / arbeidsoppgaver Anskaffelser er en strategisk…",
      "deadline": "📅 15.09.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/305558",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.194Z",
      "dateFound": "2026-08-18T08:41:18.194Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-university-of-oslo--phd-molecular-immunology",
      "country": "norway",
      "tier": "high",
      "type": "phd",
      "org": "Universitetet i Oslo",
      "score": 95,
      "title": "PhD Research Fellow in Molecular Immunology",
      "tags": [
        "🎓 PhD",
        "📍 Oslo"
      ],
      "why": "PhD Research Fellow in Molecular Immunology About the position More about the position The fellowship period is 3 years and devoted to carrying out a project on…",
      "deadline": "📅 27.08.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/305939",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.199Z",
      "dateFound": "2026-08-18T08:41:18.199Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-nord-universitet--evolutionary-genomics",
      "country": "norway",
      "tier": "high",
      "type": "phd",
      "org": "Nord universitet",
      "score": 95,
      "title": "PhD position in evolutionary genomics",
      "tags": [
        "🎓 PhD",
        "📍 Bodø"
      ],
      "why": "PhD position in evolutionary genomics Faculty of Biosciences and Aquaculture (FBA) This is Nord University Would you like to help create knowledge that makes a …",
      "deadline": "📅 31.08.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/301363",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.201Z",
      "dateFound": "2026-08-18T08:41:18.201Z",
      "roleType": "phd",
      "domain": "epigenetics",
      "sourceType": "academic"
    },
    {
      "id": "norway-ntnu--inntil-7-stillinger",
      "country": "norway",
      "tier": "high",
      "type": "phd",
      "org": "NTNU - Norges teknisk-naturvitenskapelige universitet",
      "score": 80,
      "title": "INNTIL 7 STIPENDIATSTILLINGER",
      "tags": [
        "🎓 PhD",
        "📍 Trondheim"
      ],
      "why": "INNTIL 7 STIPENDIATSTILLINGER Det humanistiske fakultet søker etter kandidater til Dette er NTNU NTNU er et breddeuniversitet med en teknisk-naturvitenskapelig …",
      "deadline": "📅 01.10.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/304877",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.210Z",
      "dateFound": "2026-08-18T08:41:18.210Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-universitetet-i-s-r-st-norge--i-management-bruk-",
      "country": "norway",
      "tier": "medium",
      "type": "phd",
      "org": "Universitetet i Sørøst-Norge",
      "score": 75,
      "title": "Stipendiat i Management:Bruk av kunstig intelligens i helseorganisasjoner og utdanningsinstitusjoner",
      "tags": [
        "🎓 PhD",
        "📍 Borre"
      ],
      "why": "Stipendiat i Management:Bruk av kunstig intelligens i helseorganisasjoner og utdanningsinstitusjoner Er du interessert i hvordan helseorganisasjoner og utdannin…",
      "deadline": "📅 31.08.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/304650",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.213Z",
      "dateFound": "2026-08-18T08:41:18.213Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-universitetet-i-s-r-st-norge--i-management-ki-in",
      "country": "norway",
      "tier": "medium",
      "type": "phd",
      "org": "Universitetet i Sørøst-Norge",
      "score": 75,
      "title": "Stipendiat i Management: KI-industrielle løsninger for bærekraftig maritim virksomhet",
      "tags": [
        "🎓 PhD",
        "📍 Borre"
      ],
      "why": "Stipendiat i Management: KI-industrielle løsninger for bærekraftig maritim virksomhet Er du interessert i hvordan kunstig intelligens kan støtte bærekraftig ind…",
      "deadline": "📅 31.08.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/304467",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.217Z",
      "dateFound": "2026-08-18T08:41:18.217Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-ntnu--i-tverrfaglig-barndomsforskning-digitale-f",
      "country": "norway",
      "tier": "high",
      "type": "phd",
      "org": "NTNU - Norges teknisk-naturvitenskapelige universitet",
      "score": 78,
      "title": "Stipendiat i tverrfaglig barndomsforskning: Digitale fellesskap, kjønn og ungdom",
      "tags": [
        "🎓 PhD",
        "📍 Trondheim"
      ],
      "why": "Stipendiat i tverrfaglig barndomsforskning: Digitale fellesskap, kjønn og ungdom Ved Institutt for pedagogikk og livslang læring (IPL), er det ledig stilling so…",
      "deadline": "📅 07.10.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/306682",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.230Z",
      "dateFound": "2026-08-18T08:41:18.230Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-ntnu--stilling-innen-dokumentasjonsforvaltning-d",
      "country": "norway",
      "tier": "medium",
      "type": "phd",
      "org": "NTNU - Norges teknisk-naturvitenskapelige universitet",
      "score": 70,
      "title": "Stipendiatstilling innen dokumentasjonsforvaltning, demokratisk beredskap og KI i offentlig sektor",
      "tags": [
        "🎓 PhD",
        "📍 Trondheim"
      ],
      "why": "Stipendiatstilling innen dokumentasjonsforvaltning, demokratisk beredskap og KI i offentlig sektor Ved Institutt for lærerutdanning er det ledig stilling som De…",
      "deadline": "📅 20.10.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/306687",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.234Z",
      "dateFound": "2026-08-18T08:41:18.234Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-vid-vitenskapelige-h-gskole--sykepleie-verneplei",
      "country": "norway",
      "tier": "medium",
      "type": "phd",
      "org": "VID vitenskapelige høgskole",
      "score": 65,
      "title": "Stipendiat innen sykepleie, vernepleie og ergoterapi (inntil 6 stillinger)",
      "tags": [
        "🎓 PhD",
        "📍 Flere"
      ],
      "why": "Stipendiat innen sykepleie, vernepleie og ergoterapi (inntil 6 stillinger) Har du ambisjoner om forskningskompetanse innen helsevitenskap? Forskningsområde VID …",
      "deadline": "📅 01.11.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/305057",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.241Z",
      "dateFound": "2026-08-18T08:41:18.241Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-vid-vitenskapelige-h-gskole--stilling",
      "country": "norway",
      "tier": "medium",
      "type": "phd",
      "org": "VID vitenskapelige høgskole",
      "score": 75,
      "title": "Stipendiatstilling",
      "tags": [
        "🎓 PhD",
        "📍 Oslo"
      ],
      "why": "Stipendiatstilling Inntil to stipendiatstillinger innen ledelse, organisasjon og verdier i praksis Senter for diakoni og profesjonell praksis Senter for diakoni…",
      "deadline": "📅 20.08.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/300692",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.242Z",
      "dateFound": "2026-08-18T08:41:18.242Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-universitetet-i-s-r-st-norge--i-management-ledel",
      "country": "norway",
      "tier": "medium",
      "type": "phd",
      "org": "Universitetet i Sørøst-Norge",
      "score": 75,
      "title": "Stipendiat i Management: Ledelse, organisering og utvikling av revisjonssektoren som følge av KI",
      "tags": [
        "🎓 PhD",
        "📍 Borre"
      ],
      "why": "Stipendiat i Management: Ledelse, organisering og utvikling av revisjonssektoren som følge av KI Er du interessert i revisjon (inkl. attestasjon av bærekraftsra…",
      "deadline": "📅 16.10.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/304593",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.245Z",
      "dateFound": "2026-08-18T08:41:18.245Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-universitetet-i-s-r-st-norge--i-management-ai-ba",
      "country": "norway",
      "tier": "high",
      "type": "phd",
      "org": "Universitetet i Sørøst-Norge",
      "score": 80,
      "title": "Stipendiat i Management: AI-basert forretningsmodell utvikling i etablerte industrier",
      "tags": [
        "🎓 PhD",
        "📍 Borre"
      ],
      "why": "Stipendiat i Management: AI-basert forretningsmodell utvikling i etablerte industrier Er du interessert i kunstig intelligens, produkt-tjenestesystemer, innovas…",
      "deadline": "📅 31.08.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/304414",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.247Z",
      "dateFound": "2026-08-18T08:41:18.247Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-ntnu--i-epidemiologi-innen-kvinnehelse-og-arbeid",
      "country": "norway",
      "tier": "high",
      "type": "phd",
      "org": "NTNU - Norges teknisk-naturvitenskapelige universitet",
      "score": 85,
      "title": "Stipendiat i epidemiologi innen kvinnehelse og arbeidsdeltakelse",
      "tags": [
        "🎓 PhD",
        "📍 Trondheim"
      ],
      "why": "Stipendiat i epidemiologi innen kvinnehelse og arbeidsdeltakelse Ved Institutt for nevromedisin og bevegelsesvitenskap er det ledig stilling som Dette er NTNU N…",
      "deadline": "📅 23.08.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/304748",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.249Z",
      "dateFound": "2026-08-18T08:41:18.249Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-universitetet-i-s-r-st-norge--i-management-digit",
      "country": "norway",
      "tier": "medium",
      "type": "phd",
      "org": "Universitetet i Sørøst-Norge",
      "score": 75,
      "title": "Stipendiat i Management: Digitaliseringsledelse og beredskap",
      "tags": [
        "🎓 PhD",
        "📍 Borre"
      ],
      "why": "Stipendiat i Management: Digitaliseringsledelse og beredskap Er du interessert i samspillet mellom digitalisering, ledelse, styring og beredskap i offentlig sek…",
      "deadline": "📅 31.08.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/304527",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.254Z",
      "dateFound": "2026-08-18T08:41:18.254Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "norway-universitetet-i-s-r-st-norge--i-management-polit",
      "country": "norway",
      "tier": "medium",
      "type": "phd",
      "org": "Universitetet i Sørøst-Norge",
      "score": 75,
      "title": "Stipendiat i Management: Politisk økonomi og ledelse",
      "tags": [
        "🎓 PhD",
        "📍 Drammen"
      ],
      "why": "Stipendiat i Management: Politisk økonomi og ledelse Er du interessert i politisk økonomi, politisk makt, institusjoner og hvordan økonomiske interesser former …",
      "deadline": "📅 31.08.2026",
      "deadlineWarn": false,
      "url": "https://www.jobbnorge.no/ledige-stillinger/stilling/304792",
      "source": "live",
      "sourceName": "norway",
      "portal": "Jobbnorge (Norway)",
      "fetchedAt": "2026-08-18T08:41:18.256Z",
      "dateFound": "2026-08-18T08:41:18.256Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "industry-novo-nordisk--senior-pkpd-modeling-scientist-mat",
      "country": "denmark",
      "tier": "stretch",
      "type": "industry",
      "org": "Novo Nordisk",
      "score": 48,
      "title": "Senior PKPD Modeling Scientist - Maternity Cover",
      "tags": [
        "🏢 Industry",
        "📍 Måløv, Denmark"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.novonordisk.com/job/M%C3%A5l%C3%B8v-Senior-PKPD-Modeling-Scientist-Maternity-Cover-Capi/1426615433/",
      "source": "live",
      "sourceName": "industry",
      "portal": "Industry Careers",
      "fetchedAt": "2026-08-18T08:41:18.270Z",
      "dateFound": "2026-08-18T08:41:18.270Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-novo-nordisk--adv-research-scientist",
      "country": "denmark",
      "tier": "stretch",
      "type": "industry",
      "org": "Novo Nordisk",
      "score": 48,
      "title": "Adv Research Scientist",
      "tags": [
        "🏢 Industry",
        "📍 Måløv, Denmark"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.novonordisk.com/job/M%C3%A5l%C3%B8v-Adv-Research-Scientist-Capi/1424246233/",
      "source": "live",
      "sourceName": "industry",
      "portal": "Industry Careers",
      "fetchedAt": "2026-08-18T08:41:18.270Z",
      "dateFound": "2026-08-18T08:41:18.270Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-novo-nordisk--laboratory-technician-for-protein-",
      "country": "denmark",
      "tier": "stretch",
      "type": "industry",
      "org": "Novo Nordisk",
      "score": 45,
      "title": "Laboratory Technician for Protein Purification",
      "tags": [
        "🏢 Industry",
        "📍 Måløv, Denmark"
      ],
      "why": "Scraped from industry. Rule-based score: 45 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.novonordisk.com/job/M%C3%A5l%C3%B8v-Laboratory-Technician-for-Protein-Purification-Capi/1425205133/",
      "source": "live",
      "sourceName": "industry",
      "portal": "Industry Careers",
      "fetchedAt": "2026-08-18T08:41:18.271Z",
      "dateFound": "2026-08-18T08:41:18.271Z",
      "roleType": "technician",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-novo-nordisk--associate-general-counsel",
      "country": "denmark",
      "tier": "stretch",
      "type": "industry",
      "org": "Novo Nordisk",
      "score": 43,
      "title": "Associate General Counsel",
      "tags": [
        "🏢 Industry",
        "📍 Bagsværd, Denmark"
      ],
      "why": "Scraped from industry. Rule-based score: 43 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.novonordisk.com/job/Bagsv%C3%A6rd-Associate-General-Counsel-Capi/1426468033/",
      "source": "live",
      "sourceName": "industry",
      "portal": "Industry Careers",
      "fetchedAt": "2026-08-18T08:41:18.271Z",
      "dateFound": "2026-08-18T08:41:18.271Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-novo-nordisk--laboratory-technician-protein-engi",
      "country": "denmark",
      "tier": "stretch",
      "type": "industry",
      "org": "Novo Nordisk",
      "score": 45,
      "title": "Laboratory Technician, Protein Engineering, Måløv, Denmark",
      "tags": [
        "🏢 Industry",
        "📍 Måløv, Denmark"
      ],
      "why": "Scraped from industry. Rule-based score: 45 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.novonordisk.com/job/M%C3%A5l%C3%B8v-Laboratory-Technician%2C-Protein-Engineering%2C-M%C3%A5l%C3%B8v%2C-Denmark-Capi/1424639333/",
      "source": "live",
      "sourceName": "industry",
      "portal": "Industry Careers",
      "fetchedAt": "2026-08-18T08:41:18.271Z",
      "dateFound": "2026-08-18T08:41:18.271Z",
      "roleType": "technician",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-novo-nordisk--translational-r-d-specialist",
      "country": "denmark",
      "tier": "stretch",
      "type": "industry",
      "org": "Novo Nordisk",
      "score": 43,
      "title": "Translational R&D Specialist",
      "tags": [
        "🏢 Industry",
        "📍 Søborg, Denmark"
      ],
      "why": "Scraped from industry. Rule-based score: 43 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.novonordisk.com/job/S%C3%B8borg-Translational-R&D-Specialist-Capi/1424327233/",
      "source": "live",
      "sourceName": "industry",
      "portal": "Industry Careers",
      "fetchedAt": "2026-08-18T08:41:18.271Z",
      "dateFound": "2026-08-18T08:41:18.271Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-novo-nordisk--quality-specialist",
      "country": "denmark",
      "tier": "stretch",
      "type": "industry",
      "org": "Novo Nordisk",
      "score": 43,
      "title": "Quality Specialist",
      "tags": [
        "🏢 Industry",
        "📍 Søborg, Denmark"
      ],
      "why": "Scraped from industry. Rule-based score: 43 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.novonordisk.com/job/S%C3%B8borg-Quality-Specialist-Capi/1421307433/",
      "source": "live",
      "sourceName": "industry",
      "portal": "Industry Careers",
      "fetchedAt": "2026-08-18T08:41:18.271Z",
      "dateFound": "2026-08-18T08:41:18.271Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-novo-nordisk--principal-clinical-pharmacology-sp",
      "country": "denmark",
      "tier": "stretch",
      "type": "industry",
      "org": "Novo Nordisk",
      "score": 43,
      "title": "Principal Clinical Pharmacology Specialist - Diabetes, Søborg, Denmark",
      "tags": [
        "🏢 Industry",
        "📍 Søborg, Denmark"
      ],
      "why": "Scraped from industry. Rule-based score: 43 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.novonordisk.com/job/S%C3%B8borg-Principal-Clinical-Pharmacology-Specialist-Diabetes%2C-S%C3%B8borg%2C-Denmark-Capi/1405454833/",
      "source": "live",
      "sourceName": "industry",
      "portal": "Industry Careers",
      "fetchedAt": "2026-08-18T08:41:18.272Z",
      "dateFound": "2026-08-18T08:41:18.272Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-novo-nordisk--specialist-for-cmc-injectable-drug",
      "country": "denmark",
      "tier": "stretch",
      "type": "industry",
      "org": "Novo Nordisk",
      "score": 43,
      "title": "Specialist for CMC Injectable Drug Product Development",
      "tags": [
        "🏢 Industry",
        "📍 Måløv, Denmark"
      ],
      "why": "Scraped from industry. Rule-based score: 43 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.novonordisk.com/job/M%C3%A5l%C3%B8v-Specialist-for-CMC-Injectable-Drug-Product-Development-Capi/1410990833/",
      "source": "live",
      "sourceName": "industry",
      "portal": "Industry Careers",
      "fetchedAt": "2026-08-18T08:41:18.272Z",
      "dateFound": "2026-08-18T08:41:18.272Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-novo-nordisk--document-automation-specialist-con",
      "country": "denmark",
      "tier": "stretch",
      "type": "industry",
      "org": "Novo Nordisk",
      "score": 43,
      "title": "Document Automation Specialist, Content Innovation & Management, Clinical Reporting",
      "tags": [
        "🏢 Industry",
        "📍 Søborg, Denmark"
      ],
      "why": "Scraped from industry. Rule-based score: 43 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.novonordisk.com/job/S%C3%B8borg-Document-Automation-Specialist%2C-Content-Innovation-&-Management%2C-Clinical-Reporting-Capi/1424896033/",
      "source": "live",
      "sourceName": "industry",
      "portal": "Industry Careers",
      "fetchedAt": "2026-08-18T08:41:18.272Z",
      "dateFound": "2026-08-18T08:41:18.272Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--cell-molecular-scientist",
      "country": "united kingdom",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 48,
      "title": "Cell & Molecular Scientist",
      "tags": [
        "🏢 Industry",
        "📍 UK - Cambridge"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/UK---Cambridge/Cell---Molecular-Scientist_R78361",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.273Z",
      "dateFound": "2026-08-18T08:41:18.273Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--biotech-associate",
      "country": "netherlands",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 48,
      "title": "Biotech Associate",
      "tags": [
        "🏢 Industry",
        "📍 NL - Geleen"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/NL---Geleen/Biotech-Associate_R77107",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.274Z",
      "dateFound": "2026-08-18T08:41:18.274Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--biotechnologist-cell-culture",
      "country": "united kingdom",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 50,
      "title": "Biotechnologist - Cell Culture",
      "tags": [
        "🏢 Industry",
        "📍 UK - Slough"
      ],
      "why": "Scraped from industry. Rule-based score: 50 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/UK---Slough/Biotechnologist---Cell-Culture_R77978-1",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.274Z",
      "dateFound": "2026-08-18T08:41:18.274Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--biotechnologist-cell-gene-therapy",
      "country": "singapore",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 40,
      "title": "Biotechnologist (Cell & Gene Therapy)",
      "tags": [
        "🏢 Industry",
        "📍 SG - Tuas, Singapore"
      ],
      "why": "Scraped from industry. Rule-based score: 40 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/SG---Tuas-Singapore/Biotechnologist-1--Cell-Gene-Therapy-_R69666",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.275Z",
      "dateFound": "2026-08-18T08:41:18.275Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--biotechnologist-20k-mammalian",
      "country": "singapore",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 40,
      "title": "Biotechnologist 20K (Mammalian)",
      "tags": [
        "🏢 Industry",
        "📍 SG - Tuas, Singapore"
      ],
      "why": "Scraped from industry. Rule-based score: 40 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/SG---Tuas-Singapore/Biotechnologist-20K--Mammalian-_R72338",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.275Z",
      "dateFound": "2026-08-18T08:41:18.275Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--lead-scientist",
      "country": "united kingdom",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 48,
      "title": "Lead Scientist",
      "tags": [
        "🏢 Industry",
        "📍 UK - Slough"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/UK---Slough/Lead-Scientist_R76770",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.276Z",
      "dateFound": "2026-08-18T08:41:18.276Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--qc-scientist",
      "country": "united kingdom",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 48,
      "title": "QC Scientist",
      "tags": [
        "🏢 Industry",
        "📍 UK - Slough"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/UK---Slough/QC-Scientist_R77567",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.276Z",
      "dateFound": "2026-08-18T08:41:18.276Z",
      "roleType": "qa-qc",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--data-scientist",
      "country": "netherlands",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 48,
      "title": "Data Scientist",
      "tags": [
        "🏢 Industry",
        "📍 NL - Geleen"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/NL---Geleen/Data-Scientist_R77324",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.276Z",
      "dateFound": "2026-08-18T08:41:18.276Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--msat-scientist",
      "country": "netherlands",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 48,
      "title": "MSAT Scientist",
      "tags": [
        "🏢 Industry",
        "📍 NL - Geleen"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/NL---Geleen/MSAT-Scientist_R77645-1",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.276Z",
      "dateFound": "2026-08-18T08:41:18.276Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--lab-automation-scientist",
      "country": "united kingdom",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 48,
      "title": "Lab Automation Scientist",
      "tags": [
        "🏢 Industry",
        "📍 UK - Slough"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/UK---Slough/Lab-Automation-Scientist_R74317",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.276Z",
      "dateFound": "2026-08-18T08:41:18.276Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-lonza--qc-scientist-method-validation",
      "country": "united kingdom",
      "tier": "stretch",
      "type": "industry",
      "org": "Lonza",
      "score": 48,
      "title": "QC Scientist - Method Validation",
      "tags": [
        "🏢 Industry",
        "📍 UK - Slough"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lonza.wd3.myworkdayjobs.com/job/UK---Slough/Lead-Scientist--Method-Validation-_R73441-1",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.277Z",
      "dateFound": "2026-08-18T08:41:18.277Z",
      "roleType": "qa-qc",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-illumina--scientist-1-assay-r-d",
      "country": "singapore",
      "tier": "stretch",
      "type": "industry",
      "org": "Illumina",
      "score": 48,
      "title": "Scientist 1 (Assay R&D)",
      "tags": [
        "🏢 Industry",
        "📍 Singapore - Woodlands - NorthCoast"
      ],
      "why": "Scraped from industry. Rule-based score: 48 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://illumina.wd1.myworkdayjobs.com/job/Singapore---Woodlands---NorthCoast/Scientist-1--Assay-R-D-_43221-JOB",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.278Z",
      "dateFound": "2026-08-18T08:41:18.278Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "industry-illumina--customer-care-specialist-2",
      "country": "netherlands",
      "tier": "stretch",
      "type": "industry",
      "org": "Illumina",
      "score": 43,
      "title": "Customer Care Specialist 2",
      "tags": [
        "🏢 Industry",
        "📍 Netherlands - Eindhoven"
      ],
      "why": "Scraped from industry. Rule-based score: 43 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://illumina.wd1.myworkdayjobs.com/job/Netherlands---Eindhoven/Customer-Care-Specialist-2_42354-JOB-1",
      "source": "live",
      "sourceName": "industry",
      "portal": "Workday API",
      "fetchedAt": "2026-08-18T08:41:18.278Z",
      "dateFound": "2026-08-18T08:41:18.278Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "industry"
    },
    {
      "id": "epfl-epfl-lausanne--laboratory-technician",
      "country": "switzerland",
      "tier": "stretch",
      "type": "phd",
      "org": "EPFL Lausanne",
      "score": 50,
      "title": "Laboratory Technician",
      "tags": [
        "🏢 Industry",
        "📍 Lausanne"
      ],
      "why": "Scraped from epfl. Rule-based score: 50 matches Kavya's profile keywords.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://careers.epfl.ch/job/Lausanne-Laboratory-Technician/1165253155/",
      "source": "live",
      "sourceName": "epfl",
      "portal": "Other",
      "fetchedAt": "2026-08-18T08:41:18.281Z",
      "dateFound": "2026-08-18T08:41:18.281Z",
      "roleType": "technician",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "leibniz-leibniz-institute-for-baltic-sea-research-iow--t",
      "country": "germany",
      "tier": "medium",
      "type": "phd",
      "org": "Leibniz Institute for Baltic Sea Research (IOW)",
      "score": 65,
      "title": "PhD candidate in the field of Harmful Algal Blooms and Phycotoxin Analysis",
      "tags": [
        "🎓 PhD",
        "📍 Warnemünde"
      ],
      "why": "Research post at Leibniz Institute for Baltic Sea Research (IOW). Location: Warnemünde.…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://www.leibniz-gemeinschaft.de/en/careers/jobs/detail/job/show/Job/phd-candidate-in-the-field-of-harmful-algal-blooms-and-phycotoxin-analysis",
      "source": "live",
      "sourceName": "leibniz",
      "portal": "Other",
      "fetchedAt": "2026-08-18T08:41:18.282Z",
      "dateFound": "2026-08-18T08:41:18.282Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "academics-universit-tsmedizin-g-ttingen-umg--cellular-mole",
      "country": "germany",
      "tier": "medium",
      "type": "phd",
      "org": "Universitätsmedizin Göttingen (UMG)",
      "score": 70,
      "title": "PhD Student Cellular & Molecular Immunology (f/m/d)",
      "tags": [
        "🎓 PhD",
        "📍 Göttingen"
      ],
      "why": "Position at Universitätsmedizin Göttingen (UMG) matching query: phd.…",
      "deadline": "📅 2026-07-30",
      "deadlineWarn": false,
      "url": "https://www.academics.com/jobs/phd-student-cellular-molecular-immunology-f-m-d-universitaetsmedizin-goettingen-umg-1110008",
      "source": "live",
      "sourceName": "academics",
      "portal": "Other",
      "fetchedAt": "2026-08-18T08:41:18.284Z",
      "dateFound": "2026-08-18T08:41:18.284Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "academics-universit-tsmedizin-g-ttingen-umg--f-m-d-klinik-",
      "country": "germany",
      "tier": "high",
      "type": "phd",
      "org": "Universitätsmedizin Göttingen (UMG)",
      "score": 80,
      "title": "PhD position (f/m/d) Klinik für Gastroenterologie, gastrointestinale Onkologie und Endokrinologie",
      "tags": [
        "🎓 PhD",
        "📍 Göttingen"
      ],
      "why": "Position at Universitätsmedizin Göttingen (UMG) matching query: phd.…",
      "deadline": "📅 2026-07-13",
      "deadlineWarn": false,
      "url": "https://www.academics.com/jobs/phd-position-f-m-d-klinik-fuer-gastroenterologie-gastrointestinale-onkologie-und-endokrinologie-universitaetsmedizin-goettingen-umg-1109538",
      "source": "live",
      "sourceName": "academics",
      "portal": "Other",
      "fetchedAt": "2026-08-18T08:41:18.284Z",
      "dateFound": "2026-08-18T08:41:18.284Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    }
  ]
};