window.KAVYA_JOBS_DB = {
  "lastUpdated": "2026-06-06T02:43:48.989Z",
  "sourceHealth": {
    "swedish": "healthy",
    "dutch": "healthy",
    "germany": "healthy",
    "danish": "healthy"
  },
  "jobs": [
    {
      "id": "swedish-karolinska-institutet--forskningsspecialist-i-ba",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 100,
      "title": "Forskningsspecialist i Bakteriologi och vacciner",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för mikrobiologi, tumör- och cellbiologi (MTC) vid Karolinska Institutet bedriver forsknin…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:941850/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.242Z",
      "dateFound": "2026-06-05T15:47:19.242Z",
      "roleType": "research-assistant",
      "domain": "toxicology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 100,
      "title": "Forskningsassistent",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Vi söker en motiverad och noggrann forskningsassistent till en forskargrupp vid Karolinska Institutet me…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:941620/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.247Z",
      "dateFound": "2026-06-05T15:47:19.247Z",
      "roleType": "research-assistant",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-till-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 100,
      "title": "Forskningsassistent till cellulär modellering av psykiatriska sjukdomar (visstidsanställning)",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Gruppen för tillämpad och utvecklinsgrelaterad neurobiologi, ledd av Carl Sellgren, söker en mycket moti…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:933187/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.253Z",
      "dateFound": "2026-06-05T15:47:19.253Z",
      "roleType": "research-assistant",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-inom-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 100,
      "title": "Forskningsassistent inom oligonukleotid-baserad diagnostik och terapi för nukleotidexpansionssjukdomar",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? Institutionen för laboratoriemedicin består av sju avdelningar inom vilka det bedrivs både forskning och unde…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:935689/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.256Z",
      "dateFound": "2026-06-05T15:47:19.256Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--gene-editing-of-human-ste",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 100,
      "title": "Research Assistant in Gene Editing of Human Stem Cells",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm",
        "Stem Cells"
      ],
      "why": "Do you want to contribute to top quality medical research? The Rydén &amp; Mejhert laboratory is a multidisciplinary research group of 15–20 members, including …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:938197/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.258Z",
      "dateFound": "2026-06-05T15:47:19.258Z",
      "roleType": "research-assistant",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--to-karolinska-institutet",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 100,
      "title": "Research assistant to Karolinska Institutet",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Do you want to contribute to top quality medical research? We are seeking a motivated research assistant to join our efforts to improve drug combination therapi…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:938876/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.261Z",
      "dateFound": "2026-06-05T15:47:19.261Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-inom-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 100,
      "title": "Forskningsassistent inom immunologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för medicin i Huddinge består av fem enheter, sex core facilities och cirka 80 oberoende f…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:936800/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.266Z",
      "dateFound": "2026-06-05T15:47:19.266Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "dutch-erasmus-mc--dc1-the-ribomethylation-nm-epitransc",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Erasmus MC",
      "score": 100,
      "title": "PhD student (DC1) The ribomethylation (Nm) epitranscriptome of prostate cancer",
      "tags": [
        "🎓 PhD",
        "📍 Rotterdam",
        "Epigenetics"
      ],
      "why": "Are you ready to join The MSCA-DN European Epitranscriptomics of Cancer Academy? We are seeking a highly motivated PhD candidate to join the Marie Skłodowska-Cu…",
      "deadline": "8 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/360726/phd-student-dc1-the-ribomethylation-nm-epitranscriptome-of-prostate-cancer/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-06-05T15:47:19.328Z",
      "dateFound": "2026-06-05T15:47:19.328Z",
      "roleType": "phd",
      "domain": "epigenetics",
      "sourceType": "academic"
    },
    {
      "id": "dutch-erasmus-mc--dc13-the-epitranscriptome-of-prostat",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Erasmus MC",
      "score": 100,
      "title": "PhD student (DC13) The epitranscriptome of prostate cancer progression",
      "tags": [
        "🎓 PhD",
        "📍 Rotterdam"
      ],
      "why": "Are you ready to join The MSCA-DN European Epitranscriptomics of Cancer Academy? We are seeking a highly motivated PhD candidate to join the Marie Skłodowska-Cu…",
      "deadline": "8 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/360725/phd-student-dc13-the-epitranscriptome-of-prostate-cancer-progression/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-06-05T15:47:19.328Z",
      "dateFound": "2026-06-05T15:47:19.328Z",
      "roleType": "phd",
      "domain": "epigenetics",
      "sourceType": "academic"
    },
    {
      "id": "dutch-maastricht-university--on-a-stem-cell-derived-mo",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Maastricht University",
      "score": 100,
      "title": "PhD candidate on a stem cell-derived model of the trabecular meshwork",
      "tags": [
        "🎓 PhD",
        "📍 Maastricht",
        "Stem Cells"
      ],
      "why": "Welcome to Maastricht University! We seek a PhD candidate to join our team developing in vitro models and cell therapies for ophthalmic diseases and conditions.…",
      "deadline": "22 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/361217/phd-candidate-on-a-stem-cell-derived-model-of-the-trabecular-meshwork/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-06-05T15:47:19.330Z",
      "dateFound": "2026-06-05T15:47:19.330Z",
      "roleType": "phd",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "dutch-leiden-university--on-circadian-clocks-in-bacter",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Universiteit Leiden",
      "score": 100,
      "title": "PhD candidate on circadian clocks in bacterial biofilms",
      "tags": [
        "🎓 PhD",
        "📍 Leiden"
      ],
      "why": "Applications are invited for a four-year PhD position on an exciting PhD project in circadian regulation of biofilm development. Project description We are hiri…",
      "deadline": "13 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/361019/phd-candidate-on-circadian-clocks-in-bacterial-biofilms/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-06-05T15:47:19.333Z",
      "dateFound": "2026-06-05T15:47:19.333Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "germany-helmholtz-centre-for-infection-research-hzi--phd",
      "country": "germany",
      "tier": "high",
      "type": "phd",
      "org": "Helmholtz Centre for Infection Research (HZI)",
      "score": 100,
      "title": "PhD in Early-Life Mucosal Immunology",
      "tags": [
        "🎓 PhD",
        "📍 Braunschweig"
      ],
      "why": "Stellenbezeichnung: PhD in Early-Life Mucosal Immunology Job advertisement no. 687 The Junior Research Group Early Life Immunity (ELIM) led by Natalia Torow, at…",
      "deadline": "15 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.daad.de/en/studying-in-germany/phd-studies-research/phd-germany/detail/helmholtz-centre-for-infection-research-hzi-10289/?phd-id=10289",
      "source": "live",
      "sourceName": "germany",
      "portal": "DAAD (Germany)",
      "fetchedAt": "2026-06-05T15:47:19.336Z",
      "dateFound": "2026-06-05T15:47:19.336Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "germany-helmholtz-zentrum-dresden-rossendorf--f-m-d-immu",
      "country": "germany",
      "tier": "high",
      "type": "phd",
      "org": "Helmholtz-Zentrum Dresden-Rossendorf",
      "score": 100,
      "title": "PhD Student (f/m/d) ImmunoFLASH: Enhancing anti-tumor CAR T immunotherapy with FLASH radiotherapy",
      "tags": [
        "🎓 PhD",
        "📍 Dresden"
      ],
      "why": "With cutting-edge research in the fields of ENERGY, HEALTH and MATTER, around 1,500 employees from more than 70 nations at Helmholtz-Zentrum Dresden-Rossendorf …",
      "deadline": "30 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.daad.de/en/studying-in-germany/phd-studies-research/phd-germany/detail/helmholtz-zentrum-dresden-rossendorf-10280/?phd-id=10280",
      "source": "live",
      "sourceName": "germany",
      "portal": "DAAD (Germany)",
      "fetchedAt": "2026-06-05T15:47:19.339Z",
      "dateFound": "2026-06-05T15:47:19.339Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--metabolic-control-of-g",
      "country": "denmark",
      "tier": "high",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 100,
      "title": "PhD fellowship in Metabolic Control of Glucose Utilization and Homeostasis",
      "tags": [
        "🎓 PhD",
        "📍 Copenhagen, Denmark"
      ],
      "why": "The University of Copenhagen is seeking a highly motivated and talented PhD fellow to commence November 15, 2026, or after agreement, in the Sakamoto Group at t…",
      "deadline": "August 10, 2026",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=162648",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-06-05T15:47:19.350Z",
      "dateFound": "2026-06-05T15:47:19.350Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-f-r-d",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 98,
      "title": "Forskningsassistent för digital patologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för medicinsk epidemiologi och biostatistik bedriver forskning inom epidemiologi och biost…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:941596/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.248Z",
      "dateFound": "2026-06-05T15:47:19.248Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--bioinformatisk-forskningsass",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Uppsala University",
      "score": 93,
      "title": "Bioinformatisk forskningsassistent inom hjärntumörforskning",
      "tags": [
        "🏢 Industry",
        "📍 Uppsala"
      ],
      "why": "Institutionen för immunologi, genetik och patologi vid Uppsala universitet har en bred forskningsprofil med starka forskargrupper inriktade på bl. a cancer, gen…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:941474/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.160Z",
      "dateFound": "2026-06-05T15:47:19.160Z",
      "roleType": "research-assistant",
      "domain": "epigenetics",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-inom-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 93,
      "title": "Forskningsassistent inom datadriven genkontroll för regenerativ medicin",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? I denna nya forskargrupp fokuserar vi på att använda syntetisk biologi för att lösa viktiga utmaningar inom r…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:942246/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.245Z",
      "dateFound": "2026-06-05T15:47:19.245Z",
      "roleType": "research-assistant",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsspecialist-inom",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 93,
      "title": "Forskningsspecialist inom preklinisk LNP-baserad RNA-leverans med inriktning pre-kliniskt arbete",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för laboratoriemedicin består av sju avdelningar inom vilka det bedrivs både forskning och…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:939559/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.254Z",
      "dateFound": "2026-06-05T15:47:19.254Z",
      "roleType": "research-assistant",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "swedish-ume-university--staff-scientist-inom-metabolomik",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Umeå University",
      "score": 93,
      "title": "Staff scientist inom metabolomik och amyloidsjukdomar, tidsbegränsad",
      "tags": [
        "🏢 Industry",
        "📍 Umeå"
      ],
      "why": "Beskrivning Tjänsten som staff scientist är placerad i Anders Olofssons forskargrupp vid Umeå universitet, inom Institutionen för klinisk mikrobiologi. Forsknin…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://umu.varbi.com/en/what:job/jobID:928025/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.301Z",
      "dateFound": "2026-06-05T15:47:19.301Z",
      "roleType": "junior-scientist",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "dutch-utrecht-university--pesticide-exposure-and-the-r",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "Universiteit Utrecht",
      "score": 93,
      "title": "PhD position — Pesticide exposure and the risk of Parkinson’s disease",
      "tags": [
        "🎓 PhD",
        "📍 Utrecht"
      ],
      "why": "Do pesticides in our environment increase the risk of Parkinson’s disease? Help uncover the answer using nationwide Dutch population data. Pesticides are widely…",
      "deadline": "11 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/361255/phd-position-pesticide-exposure-and-the-risk-of-parkinsons-disease/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-06-05T15:47:19.328Z",
      "dateFound": "2026-06-05T15:47:19.328Z",
      "roleType": "phd",
      "domain": "toxicology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--forskningsingenj-r",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Uppsala University",
      "score": 90,
      "title": "Forskningsingenjör",
      "tags": [
        "🏢 Industry",
        "📍 Uppsala"
      ],
      "why": "Institutionen för immunologi, genetik och patologi vid Uppsala universitet har en bred forskningsprofil med starka forskargrupper inriktade på bl. a cancer, gen…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:942929/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.160Z",
      "dateFound": "2026-06-05T15:47:19.160Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--forskningsingenj-r-clinical-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Uppsala University",
      "score": 90,
      "title": "Forskningsingenjör - Clinical Genomics Uppsala",
      "tags": [
        "🏢 Industry",
        "📍 Uppsala"
      ],
      "why": "med placering vid Institutionen för immunologi, genetik och patologi, Rudbecklaboratoriet, med uppdrag att utveckla metoder och analysera prover med avancerade …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:940560/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.169Z",
      "dateFound": "2026-06-05T15:47:19.169Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "dutch-university-of-groningen--molecular-pharmacology",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "University of Groningen",
      "score": 90,
      "title": "PhD student Molecular Pharmacology",
      "tags": [
        "🎓 PhD",
        "📍 Groningen"
      ],
      "why": "The Groningen Research Institute of Pharmacy (GRIP) of the Faculty of Science and Engineering has a position for a PhD candidate in the department of molecular …",
      "deadline": "6 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/361043/phd-student-molecular-pharmacology/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-06-05T15:47:19.331Z",
      "dateFound": "2026-06-05T15:47:19.331Z",
      "roleType": "phd",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "dutch-tu-delft--analysis-of-partial-differential-equat",
      "country": "netherlands",
      "tier": "high",
      "type": "phd",
      "org": "TU Delft",
      "score": 90,
      "title": "PhD Position Analysis of Partial Differential Equations",
      "tags": [
        "🎓 PhD",
        "📍 Delft"
      ],
      "why": "Job description The Delft Institute for Applied Mathematics (DIAM) at Delft University of Technology (TU Delft) invites applications for a full-time PhD positio…",
      "deadline": "1 Jul 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/360941/phd-position-analysis-of-partial-differential-equations/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-06-05T15:47:19.332Z",
      "dateFound": "2026-06-05T15:47:19.332Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--i-tum-rbiologi",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Lund University",
      "score": 85,
      "title": "Doktorand i tumörbiologi",
      "tags": [
        "🎓 PhD",
        "📍 Lund"
      ],
      "why": "Your expertise in developmental epigenomics, DNA methylation, molecular toxicology, and Caco-2 models aligns strongly with tumor biology.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:941795/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.205Z",
      "dateFound": "2026-06-05T15:47:19.205Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--projektassistent-i-klinisk-gene",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Lund University",
      "score": 85,
      "title": "Projektassistent i klinisk genetik",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Till Avdelningen för klinisk genetik, Institutionen för laboratoriemedicin, söker vi en projektassistent som kommer att arbeta inom…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:936531/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.209Z",
      "dateFound": "2026-06-05T15:47:19.209Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--stipendium-p-grund-eller-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 85,
      "title": "Stipendium på grund-eller avancerad nivå inom in situ-bioingenjörsvetenskap av extracellulära vesiklar",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för laboratoriemedicin består av sju avdelningar inom vilka det bedrivs både forskning och…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:939890/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.243Z",
      "dateFound": "2026-06-05T15:47:19.243Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-ume-university--i-v-xtbiologi-inom-funktionell-g",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Umeå University",
      "score": 85,
      "title": "Doktorand i växtbiologi inom funktionell genomik i barrträd",
      "tags": [
        "🎓 PhD",
        "📍 Umeå"
      ],
      "why": "Doktorand i växtbiologi inom funktionell genomik i barrträd Institutionen för fysiologisk botanik Institutionen för fysiologisk botanik vid Umeå universitet utl…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://umu.varbi.com/en/what:job/jobID:936654/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.297Z",
      "dateFound": "2026-06-05T15:47:19.297Z",
      "roleType": "phd",
      "domain": "epigenetics",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--laboratory-assistant-p",
      "country": "denmark",
      "tier": "high",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 85,
      "title": "Laboratory assistant position in the Wennerberg Group at BRIC",
      "tags": [
        "🏢 Industry",
        "📍 Copenhagen, Denmark"
      ],
      "why": "The Wennerberg Group at the Biotech and Research Innovation Center (BRIC), University of Copenhagen, is looking for a part-time laboratory assistant for laborat…",
      "deadline": "5 June 2026",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=162429",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-06-05T15:47:19.343Z",
      "dateFound": "2026-06-05T15:47:19.343Z",
      "roleType": "technician",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsspecialist-i-l-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 83,
      "title": "Forskningsspecialist i läkemedelsutveckling",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? Institutionen för mikrobiologi, tumör- och cellbiologi (MTC) vid Karolinska Institutet bedriver forskning och…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:943257/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.237Z",
      "dateFound": "2026-06-05T15:47:19.237Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistenttj-nst",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 83,
      "title": "Forskningsassistenttjänst inom ”Molekylära mekanismer bakom neurodegenerativa sjukdomar”",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Forskargruppen Vi söker en forskningsassistent till Axel Abeleins forskargrupp. Forskargruppen studerar …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:931279/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.249Z",
      "dateFound": "2026-06-05T15:47:19.249Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-inom-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 83,
      "title": "Forskningsassistent inom Hematopoes och stamcellsbiologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm",
        "Stem Cells"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för laboratoriemedicin på Karolinska Institutet består av sju avdelningar och är verksam i…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:940415/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.255Z",
      "dateFound": "2026-06-05T15:47:19.255Z",
      "roleType": "research-assistant",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "swedish-stockholm-university--forskningsassistent-i-milj",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Stockholm University",
      "score": 83,
      "title": "Forskningsassistent i miljövetenskap",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Institutionen för miljövetenskap (ACES) är en av de större institutionerna inom Naturvetenskapliga fakulteten. Institutionen består av fyra enheter med cirka 17…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://su.varbi.com/en/what:job/jobID:939302/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.278Z",
      "dateFound": "2026-06-05T15:47:19.278Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--amanuens-i-grundutbildning-inom",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Lund University",
      "score": 80,
      "title": "Amanuens i grundutbildning, inom ämnesområdet Diagnostisk radiologi 10%",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Forskargruppen är inriktad på neurodegenerativa sjukdomar, med särskilt fokus på Parkinsons sjukdom och normaltryckshydrocefalus (N…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:939914/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.208Z",
      "dateFound": "2026-06-05T15:47:19.208Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--i-translationell-neurogenetik",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Lund University",
      "score": 80,
      "title": "Doktorand i translationell neurogenetik",
      "tags": [
        "🎓 PhD",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Anställningen är placerad vid Enheten för translationell neurogenetik, Institutionen för experimentell medicinsk vetenskap, Medicin…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:934582/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.221Z",
      "dateFound": "2026-06-05T15:47:19.221Z",
      "roleType": "phd",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--laboratoriesamordnare-ino",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 80,
      "title": "Laboratoriesamordnare inom dermatologi och immunologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för medicin, Solna, är en av de största kliniska institutionerna vid Karolinska Institutet…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:934429/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.263Z",
      "dateFound": "2026-06-05T15:47:19.263Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--i-epidemiologi-med-fokus-p-h-ls",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Lund University",
      "score": 78,
      "title": "Doktorand i epidemiologi med fokus på hälsoeffekter av tatuering",
      "tags": [
        "🎓 PhD",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Forskargruppen för epidemiologi vid Avdelningen för arbets- och miljömedicin, Lunds universitet, bedriver forskning om hur faktorer…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:937898/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.224Z",
      "dateFound": "2026-06-05T15:47:19.224Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-inom-",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 78,
      "title": "Forskningsassistent inom vävnadsanalys",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Staffan Strömblads forskargrupp på Institutionen för Medicin, Huddinge, söker en Forskningsassistent. Fo…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:943334/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.240Z",
      "dateFound": "2026-06-05T15:47:19.240Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--undergraduate-studies-in-",
      "country": "sweden",
      "tier": "high",
      "type": "industry",
      "org": "Karolinska Institutet",
      "score": 78,
      "title": "Undergraduate studies in experimental liver disease research, temporary position (Scholarship)",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Do you want to contribute to top quality medical research? The Romeo lab aims to understand the biological and genetic mechanisms that drive metabolic dysfuncti…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:941979/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.244Z",
      "dateFound": "2026-06-05T15:47:19.244Z",
      "roleType": "industry-scientist",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--i-molekyl-rmedicin-experimen",
      "country": "sweden",
      "tier": "high",
      "type": "phd",
      "org": "Uppsala University",
      "score": 77,
      "title": "Doktorand i molekylärmedicin/experimentell dermatologi",
      "tags": [
        "🎓 PhD",
        "📍 Uppsala"
      ],
      "why": "Vill du arbeta med banbrytande forskning om icke-kodande RNA vid hudcancer och inflammatoriska hudsjukdomar, med stöd av kompetenta och trevliga kollegor i en i…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:941067/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.178Z",
      "dateFound": "2026-06-05T15:47:19.178Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--projektassistent-till-forskargr",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Lund University",
      "score": 75,
      "title": "Projektassistent till forskargruppen för klinisk minnesforskning",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Beskrivning av forskargruppen Forskargruppen Clinical Memory Research vid Institutionen för kliniska vetenskaper Malmö bedriver ledande forskning om biomarkörer…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:925164/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.228Z",
      "dateFound": "2026-06-05T15:47:19.228Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--klinisk-assistent-inom-ep",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 75,
      "title": "Klinisk assistent inom epidemiologi med inriktning mot gastroenterologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bedriva spännande forskning? Institutionen för medicinsk epidemiologi och biostatistik bedriver forskning inom epidemiologi inom ett brett spektrum av o…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:938663/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.260Z",
      "dateFound": "2026-06-05T15:47:19.260Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "dutch-utrecht-university--biofabrication-optogenetics-",
      "country": "netherlands",
      "tier": "medium",
      "type": "phd",
      "org": "Universiteit Utrecht",
      "score": 75,
      "title": "PhD candidate in biofabrication, optogenetics and synthetic biology technologies",
      "tags": [
        "🎓 PhD",
        "📍 Utrecht"
      ],
      "why": "Are you interested in developing the latest biotechnology and biofabrication technologies? Join our research team! In this PhD position, you will conduct resear…",
      "deadline": "24 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/361446/phd-candidate-in-biofabrication-optogenetics-and-synthetic-biology-technologies/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-06-05T15:47:19.329Z",
      "dateFound": "2026-06-05T15:47:19.329Z",
      "roleType": "phd",
      "domain": "stem-cell",
      "sourceType": "academic"
    },
    {
      "id": "danish-aarhus-university--academic-employee-ac-tap-with",
      "country": "denmark",
      "tier": "medium",
      "type": "phd",
      "org": "Aarhus University",
      "score": 75,
      "title": "Academic employee (AC-TAP) within infection and cancer immunology",
      "tags": [
        "🏢 Industry",
        "📍 Aarhus C, Denmark"
      ],
      "why": "Department of Biomedicine - Research and Education, Bartholin…",
      "deadline": "7 Jun 2026",
      "deadlineWarn": false,
      "url": "https://international.au.dk/about/profile/vacant-positions/job/academic-employee-ac-tap-within-infection-and-cancer-immunology",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-06-05T15:47:19.354Z",
      "dateFound": "2026-06-05T15:47:19.354Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-amanu",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 73,
      "title": "Forskningsassistent / amanuens",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? KIND är ett internationellt ledande center med cirka 60 medarbetare från olika professioner. Vi bedriver…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:942626/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.246Z",
      "dateFound": "2026-06-05T15:47:19.246Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "danish-aarhus-university--in-vivo-experiment-specialist",
      "country": "denmark",
      "tier": "medium",
      "type": "phd",
      "org": "Aarhus University",
      "score": 73,
      "title": "In vivo experiment specialist for investigation of disease mechanisms and the effects of new potential treatments in Parkinson’s Disease",
      "tags": [
        "🏢 Industry",
        "📍 Aarhus C, Denmark"
      ],
      "why": "Scraped from danish. Rule-based score: 73 matches Kavya's profile keywords.",
      "deadline": "7 Jun 2026",
      "deadlineWarn": false,
      "url": "https://international.au.dk/about/profile/vacant-positions/job/in-vivo-experiment-specialist-for-investigation-of-disease-mechanisms-and-the-effects-of-new-potential-treatments-in-parkinsons-disease",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-06-05T15:47:19.354Z",
      "dateFound": "2026-06-05T15:47:19.354Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--metabolic-research-and-ln",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 72,
      "title": "Research Assistant in Metabolic Research and lncRNA in Adipocytes",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Do you want to contribute to top quality medical research? The adipocyte expresses over 7000 long non-coding RNAs (lncRNAs), many uniquely expressed in fat cell…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:942989/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.239Z",
      "dateFound": "2026-06-05T15:47:19.239Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--i-maskininl-rning-med-fokus-",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Uppsala University",
      "score": 70,
      "title": "Doktorand i maskininlärning med fokus på matematiska grunder för osäkerhetskvantifiering inom djupinlärning",
      "tags": [
        "🎓 PhD",
        "📍 Uppsala"
      ],
      "why": "Är du intresserad av att utveckla matematiskt välgrundade metoder för osäkerhetskvantifiering inom djupinlärning, med särskilt fokus på stora språkmodeller för …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:943164/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.172Z",
      "dateFound": "2026-06-05T15:47:19.172Z",
      "roleType": "phd",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--projektassistent-inom-geneti",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Uppsala University",
      "score": 70,
      "title": "Projektassistent inom genetiska studier av autoimmuna och kardiovaskulära sjukdomar",
      "tags": [
        "🏢 Industry",
        "📍 Uppsala"
      ],
      "why": "Är du intresserad av att arbeta i forskningsfronten inom immunogenomik och komplexa sjukdomar, i en samarbetsinriktad och internationellt präglad miljö? Uppsala…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:941087/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.176Z",
      "dateFound": "2026-06-05T15:47:19.176Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--i-medicinsk-str-lningsfysik",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Lund University",
      "score": 70,
      "title": "Doktorand i Medicinsk Strålningsfysik",
      "tags": [
        "🎓 PhD",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Vid forskargruppen Medicinsk strålningsfysik, Institutionen för Translationell Medicin, Malmö, bedrivs forskning inom det tvärveten…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:940354/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.210Z",
      "dateFound": "2026-06-05T15:47:19.210Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--klinisk-assistent-s-kes-t",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 70,
      "title": "Klinisk assistent sökes till institutionen för Laboratoriemedicin",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för laboratoriemedicin består av sju avdelningar inom vilka det bedrivs både forskning och…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:942123/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.238Z",
      "dateFound": "2026-06-05T15:47:19.238Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-kth-royal-institute-of-technology--inom-djupinl-",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "KTH Royal Institute of Technology",
      "score": 70,
      "title": "Doktorand inom djupinlärning för biologiska system",
      "tags": [
        "🎓 PhD",
        "📍 Stockholm"
      ],
      "why": "Projektbeskrivning Forskarutbildningsämne: Elektro- och systemteknik Institutionen för beslut- och reglersystem (DCS) söker för närvarande en doktorand med en s…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://kth.varbi.com/en/what:job/jobID:928557/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.323Z",
      "dateFound": "2026-06-05T15:47:19.323Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--forskningsassistent-inom-hum",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Uppsala University",
      "score": 68,
      "title": "Forskningsassistent inom human fettvävsmetabolism",
      "tags": [
        "🏢 Industry",
        "📍 Uppsala"
      ],
      "why": "Är du intresserad av att arbeta med metabol forskning inom fettväv, med stöd av kompetenta och trevliga kollegor i en internationell miljö? Vi välkomnar dig att…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:943713/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.166Z",
      "dateFound": "2026-06-05T15:47:19.166Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-med-f",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 68,
      "title": "Forskningsassistent med fokus på neurodegenerativa och psykologiska sjukdomar",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Vid Enheten för integrativ epidemiologi är vårt övergripande mål att förbättra förståelsen av orsaker oc…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:942303/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.240Z",
      "dateFound": "2026-06-05T15:47:19.240Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-i-psy",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 68,
      "title": "Forskningsassistent i psykiatrisk epidemiologi och genetik",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? Institutionen för medicinsk epidemiologi och biostatistik bedriver forskning inom epidemiologi och biostatist…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:941344/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.251Z",
      "dateFound": "2026-06-05T15:47:19.251Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--amanuens-till-meb",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 68,
      "title": "Amanuens till MEB",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för medicinsk epidemiologi och biostatistik bedriver forskning inom epidemiologi och biost…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:940340/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.255Z",
      "dateFound": "2026-06-05T15:47:19.255Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistenter-tim",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 68,
      "title": "Forskningsassistenter (timanställning) till projekt om perinatal farmakoepidemiologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för medicinsk epidemiologi och biostatistik bedriver forskning inom epidemiologi och biost…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:939592/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.258Z",
      "dateFound": "2026-06-05T15:47:19.258Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-i-bio",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 68,
      "title": "Forskningsassistent i biostatistik med fokus på överlevnadsanalys",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Institutionen för medicinsk epidemiologi och biostatistik bedriver forskning inom epidemiologi och biost…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:938695/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.261Z",
      "dateFound": "2026-06-05T15:47:19.261Z",
      "roleType": "research-assistant",
      "domain": "toxicology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-i-psy",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 68,
      "title": "Forskningsassistent i psykiatrisk epidemiologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till en bättre hälsa för alla? Institutionen för medicinsk epidemiologi och biostatistik bedriver forskning inom epidemiologi och biostatistik ino…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:935928/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.269Z",
      "dateFound": "2026-06-05T15:47:19.269Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-stockholm-university--forskningsassistent-i-cell",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Stockholm University",
      "score": 68,
      "title": "Forskningsassistent i cell och molekylärbiologi",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Institutionen för molekylär biovetenskap, Wenner-Grens institut (MBW) bedriver experimentell grundforskning inom molekylär cellbiologi, intergrativ biologi och …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://su.varbi.com/en/what:job/jobID:940342/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.275Z",
      "dateFound": "2026-06-05T15:47:19.275Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-stockholm-university--forskningsassistent-med-fo",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Stockholm University",
      "score": 68,
      "title": "Forskningsassistent med fokus på biogeokemi på tundra",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Institutionen för miljövetenskap är en av de större institutionerna inom Naturvetenskapliga fakulteten. Institutionen består av fyra enheter med drygt 170 anstä…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://su.varbi.com/en/what:job/jobID:934686/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.283Z",
      "dateFound": "2026-06-05T15:47:19.283Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "dutch-utrecht-university--phd-on-advanced-statistical-",
      "country": "netherlands",
      "tier": "medium",
      "type": "phd",
      "org": "Universiteit Utrecht",
      "score": 68,
      "title": "PhD on Advanced Statistical and AI Methods for Multi-omic Integration",
      "tags": [
        "🎓 PhD",
        "📍 Utrecht"
      ],
      "why": "Excited to apply advanced statistics, machine learning, and AI to study how environmental exposures drive molecular pathways and multimorbidity? At the Institut…",
      "deadline": "27 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/361259/phd-on-advanced-statistical-and-ai-methods-for-multi-omic-integration/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-06-05T15:47:19.329Z",
      "dateFound": "2026-06-05T15:47:19.329Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--f-r-projekt-inom-glymfatisk-hj-",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Lund University",
      "score": 65,
      "title": "Doktorand för projekt inom glymfatisk hjärnstädning",
      "tags": [
        "🎓 PhD",
        "📍 Lund"
      ],
      "why": "Your background in neurodegeneration disease modeling and dorsal forebrain differentiation offers a foundational fit for brain research.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:935563/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.229Z",
      "dateFound": "2026-06-05T15:47:19.229Z",
      "roleType": "phd",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--forskningsassistent",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Uppsala University",
      "score": 65,
      "title": "Forskningsassistent",
      "tags": [
        "🏢 Industry",
        "📍 Uppsala"
      ],
      "why": "Your strong research techniques in epigenomics, cell culture, and molecular toxicology align with general university research needs.",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:942977/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.162Z",
      "dateFound": "2026-06-05T15:47:19.162Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--biomedicinsk-analytiker",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Uppsala University",
      "score": 65,
      "title": "Biomedicinsk analytiker",
      "tags": [
        "🏢 Industry",
        "📍 Uppsala"
      ],
      "why": "Institutionen för farmaceutisk biovetenskap Institutionen för farmaceutisk biovetenskap är en interdisciplinär miljö där 10 forskningsområden arbetar för att bi…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:943549/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.164Z",
      "dateFound": "2026-06-05T15:47:19.164Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--projektassistent-vid-institutio",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Lund University",
      "score": 65,
      "title": "Projektassistent vid institutionen för processteknik och tillämpad biovetenskap",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Detta projekt är ett samarbetsprojekt mellan avdelningen för livsmedel och läkemedel, PLE och avdelningen för tillämpad biokemi, ke…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:940991/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.207Z",
      "dateFound": "2026-06-05T15:47:19.207Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--studentmedarbetare-inom-laborat",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Lund University",
      "score": 65,
      "title": "Studentmedarbetare inom laboratorieverksamhet",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Studentmedarbetaren kommer att vara placerad vid avdelningen för molekylär hematologi och immunologi, ILM, Medicinska fakulteten. S…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:933999/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.227Z",
      "dateFound": "2026-06-05T15:47:19.227Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-ume-university--i-till-mpad-fysik-med-inriktning",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Umeå University",
      "score": 65,
      "title": "Doktorand i tillämpad fysik med inriktning mot medicinsk teknik och neurovetenskap",
      "tags": [
        "🎓 PhD",
        "📍 Umeå"
      ],
      "why": "Institutionen för tillämpad fysik och elektronik har idag ca 100 anställda och bedriver forskning inom områden såsom energiteknik, laserspektroskopi, elektronik…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://umu.varbi.com/en/what:job/jobID:939933/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.290Z",
      "dateFound": "2026-06-05T15:47:19.290Z",
      "roleType": "phd",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-ume-university--projektassistent-inom-kognitiv-n",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Umeå University",
      "score": 65,
      "title": "Projektassistent inom Kognitiv Neurovetenskap",
      "tags": [
        "🏢 Industry",
        "📍 Umeå"
      ],
      "why": "Institutionen för Medicinsk och translationell biologi vid Medicinska fakulteten söker nu en projektassistent till ett forskningsprojekt inom kognitiv neurovete…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://umu.varbi.com/en/what:job/jobID:936661/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.298Z",
      "dateFound": "2026-06-05T15:47:19.298Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-ume-university--i-kemi-med-inriktning-mot-biokem",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Umeå University",
      "score": 65,
      "title": "Doktorand i kemi, med inriktning mot biokemi",
      "tags": [
        "🎓 PhD",
        "📍 Umeå"
      ],
      "why": "Kemiska institutionen söker en doktorand i kemi med inriktning mot biokemi. Doktorandens projekt kommer att fokusera på sanering av tungmetaller med hjälp av mi…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://umu.varbi.com/en/what:job/jobID:933652/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.299Z",
      "dateFound": "2026-06-05T15:47:19.299Z",
      "roleType": "phd",
      "domain": "toxicology",
      "sourceType": "academic"
    },
    {
      "id": "danish-aarhus-university--cell-biologist-ac-tap-for-inv",
      "country": "denmark",
      "tier": "medium",
      "type": "phd",
      "org": "Aarhus University",
      "score": 65,
      "title": "Cell biologist (AC-TAP) for investigation of disease mechanisms and the effects of new potential treatments in Parkinson’s Disease",
      "tags": [
        "🏢 Industry",
        "📍 Aarhus C, Denmark"
      ],
      "why": "Scraped from danish. Rule-based score: 65 matches Kavya's profile keywords.",
      "deadline": "7 Jun 2026",
      "deadlineWarn": false,
      "url": "https://international.au.dk/about/profile/vacant-positions/job/cell-biologist-ac-tap-for-investigation-of-disease-mechanisms-and-the-effects-of-new-potential-treatments-in-parkinsons-disease",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-06-05T15:47:19.354Z",
      "dateFound": "2026-06-05T15:47:19.354Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-inom-",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 60,
      "title": "Forskningsassistent inom utveckling av nanopartikelanalys med fokus på extracellulära vesiklar",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? Institutionen för laboratoriemedicin består av sju avdelningar som bedriver både forskning och undervisning. …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:937967/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.260Z",
      "dateFound": "2026-06-05T15:47:19.260Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningssk-terska-r-ntg",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 60,
      "title": "Forskningssköterska/röntgensjuksköterska med mammografikompetens till KARMA Studiecenter",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra kvinnors hälsa? KARMA-projektet (Karmaprojektet.se) är ett unikt samarbete mellan forskare vid Karolinska Institutet och klinik…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:938099/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.262Z",
      "dateFound": "2026-06-05T15:47:19.262Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-stockholm-university--i-milj-vetenskap-med-fokus",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Stockholm University",
      "score": 60,
      "title": "Doktorand i miljövetenskap med fokus på mikroplaster och arktiska moln",
      "tags": [
        "🎓 PhD",
        "📍 Stockholm"
      ],
      "why": "Institutionen för miljövetenskap är en av de större institutionerna inom Naturvetenskapliga fakulteten. Institutionen består av fyra enheter med drygt 170 anstä…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://su.varbi.com/en/what:job/jobID:942566/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.273Z",
      "dateFound": "2026-06-05T15:47:19.273Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--and-the-genetic-archit",
      "country": "denmark",
      "tier": "medium",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 60,
      "title": "Research Assistant and PhD fellow in the Genetic architecture of skeletal muscle",
      "tags": [
        "🎓 PhD",
        "📍 Copenhagen, Denmark"
      ],
      "why": "The University of Copenhagen is seeking a highly motivated and talented PhD fellow to commence November 15, 2026, or after agreement in the Loos Group at the No…",
      "deadline": "August 10, 2026",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=162689",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-06-05T15:47:19.352Z",
      "dateFound": "2026-06-05T15:47:19.352Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--1-2-positions-in-single-c",
      "country": "sweden",
      "tier": "medium",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 58,
      "title": "Research assistant (1–2 positions) in single-cell proteomics of mitochondrial disease",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Do you want to contribute to top quality medical research? The Department of Medical Biochemistry and Biophysics (MBB) is one of the largest departments at Karo…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:937401/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.264Z",
      "dateFound": "2026-06-05T15:47:19.264Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--sequencing-specialist-",
      "country": "denmark",
      "tier": "medium",
      "type": "industry",
      "org": "University of Copenhagen",
      "score": 58,
      "title": "Sequencing Specialist at the Genomics Research Infrastructure, Center for Core Facilities, University of Copenhagen",
      "tags": [
        "🏢 Industry",
        "📍 Copenhagen, Denmark"
      ],
      "why": "The Center for Core Facilities (CCF) at the Faculty of Health and Medical Sciences (SUND), University of Copenhagen, is recruiting a highly motivated and ambiti…",
      "deadline": "7 June 2026",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=161046",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-06-05T15:47:19.344Z",
      "dateFound": "2026-06-05T15:47:19.344Z",
      "roleType": "industry-scientist",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "danish-university-of-copenhagen--research-assistent-and",
      "country": "denmark",
      "tier": "medium",
      "type": "phd",
      "org": "University of Copenhagen",
      "score": 58,
      "title": "Research Assistent and PhD in Precision Medicine from Graph-Based Medical Digital Twins",
      "tags": [
        "🎓 PhD",
        "📍 Copenhagen, Denmark"
      ],
      "why": "The University of Copenhagen is seeking a highly motivated and talented PhD fellow to commence November 15, 2026, or after agreement in the Rasmussen Group at t…",
      "deadline": "August 10, 2026",
      "deadlineWarn": false,
      "url": "https://employment.ku.dk/all-vacancies/?show=162680",
      "source": "live",
      "sourceName": "danish",
      "portal": "Danish Portals",
      "fetchedAt": "2026-06-05T15:47:19.351Z",
      "dateFound": "2026-06-05T15:47:19.351Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--translationell-forskning-om-",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Uppsala University",
      "score": 55,
      "title": "Doktorand: Translationell forskning om metabola sjukdomar",
      "tags": [
        "🎓 PhD",
        "📍 Uppsala"
      ],
      "why": "Institutionen för medicinska vetenskaper är en stor klinisk institution med ca 250 anställda och över 900 personer som är anknutna via Akademiska Sjukhuset. Ins…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:943760/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.167Z",
      "dateFound": "2026-06-05T15:47:19.167Z",
      "roleType": "phd",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-uppsala-university--i-h-lsoekonomi-med-fokus-p-p",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Uppsala University",
      "score": 55,
      "title": "Doktorand i hälsoekonomi med fokus på patientcentrerad vård och evidensbaserade beslutsstöd (MSCA HEPARD)",
      "tags": [
        "🎓 PhD",
        "📍 Uppsala",
        "MSCA · Fully Funded"
      ],
      "why": "Centrum för hälsoekonomisk forskning (HEFUU) vid Uppsala universitet söker en doktorand. HEFUU är ett tvärvetenskapligt forskningscentrum med fokus på effektiv …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://uu.varbi.com/en/what:job/jobID:938198/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.185Z",
      "dateFound": "2026-06-05T15:47:19.185Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--projektassistent-inom-genetik-o",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Lund University",
      "score": 55,
      "title": "Projektassistent inom genetik och diabetes med lönebidrag",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Beskrivning av arbetsplatsen Forskargruppen för genetik och diabetes bedriver forskning inom precisionsmedicin och den metabola komplexiteten vid typ 2-diabetes…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:940129/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.217Z",
      "dateFound": "2026-06-05T15:47:19.217Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--post-doc-in-bioinformatic",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 55,
      "title": "Post doc in Bioinformatics focusing on RNA biology and metabolic disease (scholarship)",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Do you want to contribute to better health for all? The Department of Laboratory Medicine (Labmed) at Karolinska Institutet conducts research with direct releva…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:930734/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.271Z",
      "dateFound": "2026-06-05T15:47:19.271Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-ume-university--senior-staff-scientist-inom-bioi",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Umeå University",
      "score": 55,
      "title": "Senior Staff Scientist inom Bioinformatik",
      "tags": [
        "🏢 Industry",
        "📍 Umeå"
      ],
      "why": "Senior Staff Scientist inom Bioinformatik Institutionen för fysiologisk botanik söker nu en Senior Staff Scientist inom bioinformatik. Anställningen är på helti…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://umu.varbi.com/en/what:job/jobID:926815/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.301Z",
      "dateFound": "2026-06-05T15:47:19.301Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "dutch-hubrecht-institute--hubrecht-institute-utrecht",
      "country": "netherlands",
      "tier": "stretch",
      "type": "phd",
      "org": "Hubrecht Institute",
      "score": 55,
      "title": "PhD student - Hubrecht Institute - Utrecht",
      "tags": [
        "🎓 PhD",
        "📍 Utrecht"
      ],
      "why": "We are looking for PhD student in the group of Dr. Francesca Mattiroli at the Hubrecht Institute. The successful candidate will work in a collaborative project …",
      "deadline": "19 Jun 2026",
      "deadlineWarn": false,
      "url": "https://www.academictransfer.com/en/jobs/360587/phd-student-hubrecht-institute-utrecht/",
      "source": "live",
      "sourceName": "dutch",
      "portal": "AcademicTransfer (Netherlands)",
      "fetchedAt": "2026-06-05T15:47:19.333Z",
      "dateFound": "2026-06-05T15:47:19.333Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-inom-",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 53,
      "title": "Forskningsassistent inom avancerad avbildning av neuronala proteiner",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till att förbättra människors hälsa? Forskargruppen som leds av Michael Ratz vid institutionen för cell- och molekylärbiologi söker en forskningsa…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:943208/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.238Z",
      "dateFound": "2026-06-05T15:47:19.238Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-i-neu",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 53,
      "title": "Forskningsassistent i neurometabolism",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Vårt laboratorium undersöker de bidirektionella autonoma och sensoriska nervkretsar som förbinder perife…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:938434/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.259Z",
      "dateFound": "2026-06-05T15:47:19.259Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-karolinska-institutet--forskningsassistent-i-sys",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Karolinska Institutet",
      "score": 53,
      "title": "Forskningsassistent i systemneurovetenskap Neurala grunder för överlevnadsbeteenden",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Vill du bidra till medicinsk forskning av toppkvalitet? Stagkourakis-laboratoriet, som ligger i toppmoderna faciliteter i gränssnittet mellan Karolinska Institu…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://ki.varbi.com/en/what:job/jobID:929940/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.270Z",
      "dateFound": "2026-06-05T15:47:19.270Z",
      "roleType": "research-assistant",
      "domain": "neurobiology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-ume-university--staff-scientist-inom-r-ntgenbase",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Umeå University",
      "score": 53,
      "title": "Staff scientist inom röntgenbaserad materialanalys och materialsyntes från sekundära strömmar",
      "tags": [
        "🏢 Industry",
        "📍 Umeå"
      ],
      "why": "Institutionen för tillämpad fysik och elektronik har för närvarande cirka 100 anställda och bedriver forskning inom maskinteknik, energiteknik, byggteknik samt …",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://umu.varbi.com/en/what:job/jobID:938546/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.293Z",
      "dateFound": "2026-06-05T15:47:19.293Z",
      "roleType": "junior-scientist",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--i-statistik-med-till-mpningar-i",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Lund University",
      "score": 50,
      "title": "Doktorand i statistik med tillämpningar inom genetik",
      "tags": [
        "🎓 PhD",
        "📍 Lund"
      ],
      "why": "Lunds universitet grundades 1666 och rankas återkommande som ett av världens främsta lärosäten. Här finns omkring 46 000 studenter och 8 500 medarbetare i Lund,…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:934816/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.230Z",
      "dateFound": "2026-06-05T15:47:19.230Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-lund-university--projektassistent-i-biokemi-stru",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Lund University",
      "score": 45,
      "title": "Projektassistent i Biokemi & Strukturbiologi",
      "tags": [
        "🏢 Industry",
        "📍 Lund"
      ],
      "why": "Ämnesbeskrivning Centrum för molekylär proteinvetenskap (CMPS), Kemiska institutionen, samlar forskare verksamma inom biokemi, molekylär biofysik, strukturbiolo…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://lu.varbi.com/en/what:job/jobID:942943/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.201Z",
      "dateFound": "2026-06-05T15:47:19.201Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-ume-university--i-spatial-statistik",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "Umeå University",
      "score": 45,
      "title": "Doktorand i spatial statistik",
      "tags": [
        "🎓 PhD",
        "📍 Umeå"
      ],
      "why": "Institutionen för matematik och matematisk statistik utlyser en anställning som doktorand i spatial statistik. Anställningen omfattar fyra års forskarutbildning…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://umu.varbi.com/en/what:job/jobID:937876/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.295Z",
      "dateFound": "2026-06-05T15:47:19.295Z",
      "roleType": "phd",
      "domain": "generic-biology",
      "sourceType": "academic"
    },
    {
      "id": "swedish-kth-royal-institute-of-technology--forskningsing",
      "country": "sweden",
      "tier": "stretch",
      "type": "phd",
      "org": "KTH Royal Institute of Technology",
      "score": 45,
      "title": "Forskningsingenjör i utveckling av tunnfilm baserade vågledare",
      "tags": [
        "🏢 Industry",
        "📍 Stockholm"
      ],
      "why": "Arbetsuppgifter Som forskningsingenjör kommer du att spela en central roll i utvecklingen av en ny plattform för tunnfilmsbaserad ferroelektriska kristaller för…",
      "deadline": "📅 Rolling",
      "deadlineWarn": false,
      "url": "https://kth.varbi.com/en/what:job/jobID:940234/",
      "source": "live",
      "sourceName": "swedish",
      "portal": "Varbi (Sweden)",
      "fetchedAt": "2026-06-05T15:47:19.312Z",
      "dateFound": "2026-06-05T15:47:19.312Z",
      "roleType": "research-assistant",
      "domain": "generic-biology",
      "sourceType": "academic"
    }
  ]
};